### ISSUE TITLE
This is awesome!!!

### ISSUE THREAD

**Issue by SyedAman** [adamrehn/ue4-docker#1]
Hey Adam! I really appreciate you doing this bro. This is mad cool.

I was going to do this all myself till I decided hmmm... maybe somebody else already did this before!

I'm curious how your Continuous Integration pipeline looks like! And if you do any automation tests etc. It's really cool to know that there are others out there who want to do CI for UE4.

**Comment by SyedAman** [comment]
Yes! Would be great if it was in the README. Please post it here too when you post the article so I can get notified, excited to read it :)

I'm going to try sending some PRs your way if there's any way I can improve this process.

**Comment by adamrehn** [comment]
I've just added a new section to the README called [Usage with Continuous Integration systems](https://github.com/adamrehn/ue4-docker#usage-with-continuous-integration-systems) to provide a list of resources for using these images in CI pipelines. So far it just contains a link to the only existing example I have to hand. Once my article is up, I'll add it to the list.

In the meantime, if you would like to do a write-up on your AWS-based CI pipeline and provide a link so that it can be added to the README, that contribution would be much appreciated.

**Comment by adamrehn** [comment]
I'm closing this issue here since the [Unreal Containers community hub](https://unrealcontainers.com/) is now the centralised source for implementation-agnostic information about using the Unreal Engine with Docker containers, so documentation about CI/CD usage will be added to the [Continuous Integration and Deployment](https://unrealcontainers.com/docs/use-cases/continuous-integration) page of the Unreal Containers documentation, rather than my own website or the ue4-docker documentation.
