### ISSUE TITLE
ue4-docker build fails on download chocolatey

### ISSUE THREAD

**Issue by funkylen** [adamrehn/ue4-docker#105]
Output of the `ue4-docker info` command:

```
ue4-docker version:         0.0.71 (latest available version is 0.0.71)
Operating system:           Windows 10 Enterprise N LTSC 2019 Version 1809 (OS Build 17763.1518)
Docker daemon version:      19.03.13
NVIDIA Docker supported:    No
Maximum image size:         200GB
Available disk space:       287.14 GiB
Total system memory:        15.94 GiB physical, 18.31 GiB virtual
Number of processors:       4 physical, 8 logical
```

Problem output:

```
PS C:\BuildTools> ue4-docker build 4.25.3 --no-engine
[ue4-docker build] COMMAND-LINE INVOCATION:
[ue4-docker build] ['ue4-docker', '4.25.3', '--no-engine']

[ue4-docker build] UNREAL ENGINE VERSION SETTINGS:
[ue4-docker build] Custom build:  No
[ue4-docker build] Release:       4.25.3
[ue4-docker build] Repository:    https://github.com/EpicGames/UnrealEngine.git
[ue4-docker build] Branch/tag:    4.25.3-release

[ue4-docker build] WINDOWS CONTAINER SETTINGS
[ue4-docker build] Isolation mode:               process
[ue4-docker build] Base OS image tag:            ltsc2019 (host OS is Windows 10 version 1809)
[ue4-docker build] Memory limit:                 No limit
[ue4-docker build] Detected max image size:      200GB
[ue4-docker build] Directory to copy DLLs from:  C:\Windows\System32

[ue4-docker build] GENERAL SETTINGS
[ue4-docker build] Not excluding any Engine components.

Retrieving the Git credentials that will be used to clone the UE4 repo
Username:
Password:


[ue4-docker build] Building image "adamrehn/ue4-build-prerequisites:ltsc2019"...
Sending build context to Docker daemon   1.85MB
Step 1/27 : ARG BASEIMAGE
Step 2/27 : FROM ${BASEIMAGE} AS dlls
 ---> 474ba6caf60d
Step 3/27 : SHELL ["cmd", "/S", "/C"]
 ---> Using cache
 ---> e2fa66994071
Step 4/27 : LABEL com.adamrehn.ue4-docker.sentinel="1"
 ---> Using cache
 ---> 7e2a77d241d2
Step 5/27 : RUN mkdir C:\GatheredDlls && echo. && echo.RUN directive complete. Docker will now commit the filesystem layer to disk. && echo.Note that for large filesystem layers this can take quite some time. && echo.Performing filesystem layer commit... && echo.
 ---> Using cache
 ---> b782ce3117b5
Step 6/27 : RUN powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && echo. && echo.RUN directive complete. Docker will now commit the filesystem layer to disk. && echo.Note that for large filesystem layers this can take quite some time. && echo.Performing filesystem layer commit... && echo.
 ---> Running in caae0e194335
Exception calling "DownloadString" with "1" argument(s): "The underlying
connection was closed: An unexpected error occurred on a receive."
At line:1 char:1
+ iex ((New-Object System.Net.WebClient).DownloadString('https://chocol ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

The command 'cmd /S /C powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && echo. && echo.RUN directive complete. Docker will now commit the filesystem layer to disk. && echo.Note that for large filesystem layers this can take quite some time. && echo.Performing filesystem layer commit... && echo.' returned a non-zero code: 1
[ue4-docker build] Error: failed to build image "adamrehn/ue4-build-prerequisites:ltsc2019".
```

**Comment by dkmartov** [comment]
Hey! I am still having trouble getting through the build, but I did solve this issue. 
Try adding  "dns": ["8.8.8.8"] to your docker json file. That fixed it for me

**Comment by TBBle** [comment]
One source of such failures is a site using [a TLS version not enabled in PowerShell](https://stackoverflow.com/a/40507904/166389). According to https://www.cdn77.com/tls-test, https://chocolatey.org/ is serving TLS 1.3 only, but since this is not affecting everyone, I assume TLS 1.3 is enabled in the ltsc2019 windows server core image, but perhaps there is a transparent proxy server at your site that is using a TLS version that is disabled in the image.

Unless it turns out everyone using ltsc2019 is having this problem. If so, it should be easy enough to replicate under `mcr.microsoft.com/windows/servercore:ltsc2019` and if this is the case, then ue4-docker can easily work around it.

That said, using Google DNS instead of the local system to fix this suggests that it is indeed something site-specific causing this problem, assuming @dkmartov has the same issue as @funkylen.

**Comment by adamrehn** [comment]
I'd be interested to hear if the suggestion by @dkmartov was able to resolve this for you, @funkylen.

On a related note, I've updated the repository's GitHub issue template in commit e5049a8 to include a question about whether users are accessing the network through a proxy server, since that crops up fairly often in issues reporting network problems.

**Comment by muit** [comment]
Can confirm @dkmartov 's solution worked for me with the same issue.

FYI: This issue would also prevent from cloning ue4 source since it also couldn't resolve github

**Comment by TBBle** [comment]
Maybe a `ue4-docker diagnostics` target could be knocked up that confirms https access to Chocolatey, GitHub, or any other known-to-be-needed endpoints. That diagnostic could _maybe_ (I'm not sure if one can do this with DockerFile) optionally override the DNS server to use Google's DNS 8.8.8.8 (or another global/public DNS provider) if the first test fails.

**Comment by adamrehn** [comment]
@TBBle I don't know about the automatic configuration part, since this issue seems to be most prevalent on Windows 10 where [ue4-docker setup](https://docs.adamrehn.com/ue4-docker/commands/setup) doesn't work, but adding a diagnostic to verify network connectivity inside running containers that suggests the DNS fix to the user in the event of a failure could definitely be helpful.

**Comment by adamrehn** [comment]
Damn, you can't set the DNS server for `docker build` using a flag, I was hoping to have the diagnostic retry with the DNS override applied in the event of failure, to provide immediate feedback on whether the fix will work rather than just telling the user that it exists and asking them to try for themself.

**Comment by adamrehn** [comment]
The new [ue4-docker diagnostics network](https://docs.adamrehn.com/ue4-docker/commands/diagnostics#checking-for-container-network-connectivity-issues) diagnostic is now live in ue4-docker version 0.0.74.
