### ISSUE TITLE
Possible to cut down image size?

### ISSUE THREAD

**Issue by Clockwork-Muse** [adamrehn/ue4-docker#11]
Building all the containers, ue4-package (and thus ue4-capture as well) is a huge 121GB.  Is it possible to cut this down some?  Or is that the result of precompiling all the shaders, and there isn't any "free" space available?

**Comment by adamrehn** [comment]
This is an issue that's been on my mind for quite some time, since the large image size makes replication across multiple CI buildslaves rather cumbersome.

The obvious candidates for removal are the Engine source code and the original (non-Installed) build that is created in the `ue4-build` image. Although these are extremely useful when hacking on the Engine code itself, only the system compiler toolchain/libraries and the Installed Build created in the `ue4-package` image are actually needed when building, testing, and packaging UE4 projects.

The solution I'm currently experimenting with is to use a [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/) to copy the Installed Build into a fresh instance of the `ue4-build-prerequisites` image, thus discarding all interim filesystem layers. There are a few hurdles I'm grappling with at the moment, primarily related to finding an elegant way to replicate the dependency installation that is performed by `Setup.sh` under Linux, but I hope to have something usable pushed to the repo soon.

**Comment by Clockwork-Muse** [comment]
One thing I've discovered so far is that the data created during packaging (as part of the ue4-package image) actually has _two_ (somewhat different) copies of the engine.  That's from the Unreal tool, not your dockerfiles specifically, but it doubles the size of that particular step.  I'm not completely sure which of the two I want, honestly (I haven't looked into it that much)

**Comment by adamrehn** [comment]
There are two kinds of duplication that occur when creating an Installed Build:

- Under Windows and Linux, a number of Engine components are built using both the `Development` and `Shipping` configurations. The presence of both configurations is necessary in order to support building, testing, and packaging projects.
- Under Windows, the Engine is built for both the `Win32` and `Win64` platform identifiers. This is necessary to support packaging projects for either 32-bit or 64-bit systems.

If you're targeting 64-bit systems exclusively and don't care about 32-bit support then it might be possible to save some space under Windows by removing the 32-bit build of the Engine. Having not tried this myself, I can't guarantee that it won't cause issues when using the resulting Installed Build, but in theory it should be possible by removing the `Win32` build steps and file references from the build graph data in the files `InstalledEngineBuild.xml` and `InstalledEngineFilters.xml`.

**Comment by Clockwork-Muse** [comment]
Ah, so is that what's going on.

**Comment by adamrehn** [comment]
In commit 90ac3ad I've added a new image called `ue4-slim` that isolates the Installed Build from `ue4-package` and strips away the Engine source code and non-Installed build. The resulting image is dramatically smaller, and preliminary testing suggests that all core functionality is working correctly. I'll continue to test and refine the new image going forward, identifying any further opportunities for size reduction.
