### ISSUE TITLE
Build with debug runs out of  disk space

### ISSUE THREAD

**Issue by muit** [adamrehn/ue4-docker#124]
Output of the `ue4-docker info` command:

```
ue4-docker version:         0.0.75 (latest available version is 0.0.75)
Operating system:           Windows Server 2019 Standard Evaluation Version 1809 (OS Build 17763.1637)
Docker daemon version:      19.03.13
NVIDIA Docker supported:    No
Maximum image size:         800GB
Available disk space:       1.54 TiB
Total system memory:        15.95 GiB physical, 24.95 GiB virtual
Number of processors:       8 physical, 16 logical
```

Hi!

I've been building successfully excluding debug with 400GB of maximum image size, however since I need debug, I tried to build with it, and it failed even though I progressively bumped the size up to 800GB.

The error Im getting. Happens during one of the latest stages of the build:
```
[ue4-docker build] [2020-12-28 13:56:28] [Available disk: 1.31 TiB] [Available memory: 10.74 GiB physical, 20.24 GiB virtual] [CPU usage: 9.00%]
failed to copy files: failed to copy directory: write \\?\Volume{ee876f12-4942-11eb-8078-d17df16cc289}\UnrealEngine\Engine\Intermediate\Build\Win64\UE4Server\Development\MovieSceneTracks\Module.MovieSceneTracks.gen.3_of_4.cpp.obj: There is not enough space on the disk.
```

(Side question: I need to build plugins in CICD for Linux and Android. I can either create my own dockerfile and install android sdk and Linux toolchain in windows, or use a Linux image as well. What sounds more feasible in your experience?)

**Comment by adamrehn** [comment]
@muit this is a known upstream bug in Windows containers and is being tracked in <https://github.com/adamrehn/ue4-docker/issues/99>.

With regards to building for Android, I haven't attempted to do that in a container yet myself, but my understanding is that the Unreal Engine does not support cross-compiling from Installed Builds of the Engine under Linux, only Windows. So if you're using an Installed Build (i.e. [ue4-minimal](https://docs.adamrehn.com/ue4-docker/building-images/available-container-images#ue4-minimal) or [ue4-full](https://docs.adamrehn.com/ue4-docker/building-images/available-container-images#ue4-full)) rather than a source build (i.e. [ue4-engine](https://docs.adamrehn.com/ue4-docker/building-images/available-container-images#ue4-engine)) then cross-compilation from Windows would be the only feasible option. This is something I'm eventually going to have to deal with myself when tackling Android support for [Admiral](https://admiral.build/) (which runs builds in container images created by ue4-docker), and I'm already dreading it. The Windows images are huge enough as it is; I shudder to think how massive they'll be with the Android SDK added on top of everything else.
