### ISSUE TITLE
Export command for Windows

### ISSUE THREAD

**Issue by aboutte** [adamrehn/ue4-docker#126]
I have a question about the `export` command in regards to Windows docker images.  My use case is I have virtual production environment (Windows EC2 instances) where Unreal Engine licensees use the Epic Game Launcher to download / compile their required version of Unreal Engine.  This works fine but it takes 5 minutes to create a new virtual workstation but an hour to get Unreal Engine running :/ I found this project and was hoping to pre-bake my required versions of Unreal Engine and then use the `export` command but I see that command is only available for Linux.

Is there some other way I could utilize this project for my use case?

**Comment by adamrehn** [comment]
@aboutte to provide some background context, there are two reasons that the [ue4-docker export](https://docs.adamrehn.com/ue4-docker/commands/export) command currently only supports Linux host systems:

- Linux is the environment in which the ability to export an Installed Build of the Unreal Engine is the most useful, given that the Epic Games launcher cannot currently be used to download Linux binaries in the manner that Windows and macOS binaries can be downloaded and users are expected to compile the Engine from source. There is [a page dedicated to this use case](https://unrealcontainers.com/docs/use-cases/linux-installed-builds) on the Unreal Containers community hub documentation.

- Copying files out of a Windows container image is not as straightforward as copying files out of a Linux container image. If a Windows container is running in process isolation mode then files can be copied while it is running, but if the container is running in Hyper-V isolation mode then files cannot be copied unless it is stopped. I didn't bother going to the effort of implementing and testing logic to handle both of these scenarios because I didn't anticipate enough people wanting this functionality to justify allocating time to it over other, higher-priority features.

At a technical level, it's certainly possible to copy the Unreal Engine binaries from the Windows version of the [ue4-minimal](https://docs.adamrehn.com/ue4-docker/building-images/available-container-images#ue4-minimal) or [ue4-full](https://docs.adamrehn.com/ue4-docker/building-images/available-container-images#ue4-full) container images to a host system with the [docker cp](https://docs.docker.com/engine/reference/commandline/cp/) command and use the Editor, but you won't be able to compile C++ code for projects and plugins without also installing Visual Studio (or at least the Visual C++ Build Tools.)

In terms of workflow for your use case, I'd recommend using a tool like [HashiCorp Packer](https://www.packer.io/) to prepare your VM images. There are a couple of approaches you could take:

- **Do everything in a single Packer configuration:** have Packer spin up a VM based on an AMI with Docker pre-installed, install Python and ue4-docker, build your container images, export the required binaries, then remove the components you no longer need (e.g. Docker, Python, ue4-docker, etc.) before installing additional components that your users require such as Visual Studio or virtual production tools. This has the benefit of being relatively simple, but means you'll need to rebuild the Unreal Engine every time you make a change to your VM image configuration and also requires cleanup steps to avoid cluttering your final VM image with build tools that your users don't need.

- **Use a split configuration to separate build and production environments:** as before, have tooling spin up a VM based on an AMI with Docker pre-installed, install everything you need for building the container images, build them and then export the Unreal Engine binaries. Once the binaries are built, zip them up into an archive and upload it to an S3 bucket, then *discard your build environment*. Then have Packer spin up a VM based on an AMI with just your base Windows installation, download the Unreal Engine binaries from your S3 bucket and extract them, and finally install the additional components that your users require. This is more complex to orchestrate, but avoids the need for cleanup steps and also allows you to rebuild your VM images independently of your Unreal Engine binaries, which will allow you to make changes to your other components (e.g. virtual production tools) a lot faster than would be the case if you needed to rebuild the Unreal Engine every time you make a change to your VM's Packer configuration.
