### ISSUE TITLE
Use non-fixed port for credentials helper

### ISSUE THREAD

**Issue by slonopotamus** [adamrehn/ue4-docker#142]
Currently, credentials endpoint uses a fixed port=9876. This becomes problematic if user wants to build multiple ue4-source images in parallel. Fixed port _in theory_ could also clash with some other third-party software. What I instead suggest is to use port=0 when binding to listen socket, then query the socket for effective port that it bound to and pass the port as docker argument. Binding to port=0 (meaning "use any available port from some predefined range") is supported in both Windows and Linux.

**Comment by slonopotamus** [comment]
This feature request could become a noop in case we move to BuildKit.

**Comment by adamrehn** [comment]
The main issue I can see with using a dynamic port number is that it makes it impossible for the [ue4-docker setup](https://docs.adamrehn.com/ue4-docker/commands/setup) command to create firewall rules to allow traffic on that port.

Back when I was adding support for BuildKit secrets when generating Dockerfiles, I actually added logic to the `ue4-docker build` command to pass secrets to the build process when performing a build directly rather than generating Dockerfiles. The [logic is currently broken](https://github.com/adamrehn/ue4-docker/blob/v0.0.85/ue4docker/build.py#L251-L257) due to using older configuration values from before I settled on the final `--opt credential-mode=secrets` syntax, but if we were to fix that up and add logic to disable the credential endpoint when BuildKit secrets are enabled then we could actually bypass issues around clashing port numbers when building Linux container images.

**Comment by adamrehn** [comment]
@slonopotamus I've fixed the broken logic in commit 62101e4647906a358d17a65aaace7a04195b1ec6, so multiple concurrent builds can now coexist under Linux when the user specifies `--opt credential-mode=secrets`. This doesn't help under Windows of course, but running concurrent builds under Windows is probably not advisable anyway given the extent to which MSVC likes to chew up RAM. Are you happy to close this, or would you like to explore options for supporting concurrent builds under Windows?

**Comment by slonopotamus** [comment]
I think we can just wait for buildkit support on Windows.
