### ISSUE TITLE
UE4-Docker w/ WSL2 

### ISSUE THREAD

**Issue by dborgesr** [adamrehn/ue4-docker#161]
Output of the `ue4-docker info` command:

```
ue4-docker build 4.26.2
[ue4-docker build] Error: could not detect Docker version. Please ensure Docker is installed.

```

Running on windows 10 w/ docker WSL2 backend, is it finding the WSL2 backend?

Is there something special I should be configuring?

--Thank you very much for the great work
--Diego

**Comment by slonopotamus** [comment]
What version of Python are you using? Try 3.7.x.

**Comment by dborgesr** [comment]
Thanks for the quick reply!

So I tried flipping to 3.7.4 and i'm still getting the same error, is there some way to point it to the relevant docker port?

**Comment by adamrehn** [comment]
@dborgesr if you run ue4-docker with the `--verbose` flag it will print the underlying error details, which can help when diagnosing issues connecting to the Docker daemon. I've just updated the code in commit 7094952 (tagged in ue4-docker v0.0.83) to always print the error details even when `--verbose` is not specified, since it occurs to me that users will pretty much always want to know why the connection failed in the event that something goes wrong.

Could you please re-run the command with either `--verbose` or ue4-docker v0.0.83 and post the error details here?

**Comment by slonopotamus** [comment]
For the record, I've seen this error caused by `pywin32` being unable to init native libs under Python 3.9, that's why I suggested trying 3.7. But definitely getting a clear error message in output is a good move because inability to talk to Docker could be caused by multiple things.

**Comment by smaradey** [comment]
@dborgesr in my case I had to explicitly allow my wsl distro as an additional distro.

Open Docker Desktop --> Settings --> Resources --> WSL Integration --> and then make sure:
- Enable integration with my default WSL distro is ticked
- and/or the specific distro of yours is ticked

**Comment by dborgesr** [comment]
Hey all, sorry for the slow reply! life..

Ran it w/ verbose:
`PS C:\WINDOWS\system32> ue4-docker --verbose
DEBUG:root:Install pypiwin32 package to enable npipe:// support
Error: could not detect Docker daemon version. Please ensure Docker is installed.`

And yup looks like something w/ pywin32, what should i do? reinstall pypiwin32?

--Thanks
