### ISSUE TITLE
Stop copying DLLs from host system and instead copy them from mcr.microsoft.com/windows image

### ISSUE THREAD

**Issue by slonopotamus** [adamrehn/ue4-docker#165]
Subj. Note that we will only be able to do this when we drop Windows Server 2016 LTSC support.

The benefit of this change is that we will be able to build ue4-build-prerequisites image even if host OS doesn't match target OS.

**Comment by TBBle** [comment]
So we don't forget, it looks like Windows Server 2022 onwards has replaced this image with [mcr.microsoft.com/windows/server/insider](https://hub.docker.com/_/microsoft-windows-server-insider) (presumably a non-insider base image will appear with the actual release...). It should be the same for our purposes, but we'll have to deal with the change at some level.

**Comment by slonopotamus** [comment]
So. We're half a year away from Windows 2016 Mainstream End Date. Maybe it's time?

**Comment by adamrehn** [comment]
I'm in favour of dropping LTSC 2016 support sooner rather than later. Needing to source DLL files from the host system makes it difficult to add new DLL files to the build prerequisites image, such as DLLs for [WARP](https://docs.microsoft.com/en-us/windows/win32/direct3darticles/directx-warp) or for use with GPU acceleration (which requires LTSC 2019 or newer anyway.)
