### ISSUE TITLE
Add support for VS2019

### ISSUE THREAD

**Issue by slonopotamus** [adamrehn/ue4-docker#172]
Subj. This is a prerequisite for #171.

Note that I am already working on this feature.

**Comment by CanisHelix** [comment]
@slonopotamus Just building this now, but I have a suspicion it's going to fail to package projects due to https://github.com/adamrehn/ue4cli/issues/35 as that occurs locally, unless 0.86 get's around this in a different way.

**Comment by slonopotamus** [comment]
ue4-minimal doesn't include ue4cli, so it cannot fail :)

**Comment by CanisHelix** [comment]
ue4-full does though unless I'm mistaken, or is ue4-full not using vs2019 if specified?

**Comment by slonopotamus** [comment]
Oh, sorry, I've mistaken this issue with #171.

Well, not everyone is using ue4cli. If ue4cli doesn't support VS2019, it would need to be fixed.

**Comment by TBBle** [comment]
I've been using ue4cli with VS2019 exclusively for years. I suspect the first issue in that ticket is only when you need to tell the system to pick one because you have both installed, or you have a BuildConfiguration.xml that points to VS2017 and you need to override it.

UE4 does not, out-of-the-box, try to use VS2017 and then fail, if VS2019 is installed.

In which case, it wouldn't affect this build, since we don't end up with two VS installs in the container, and don't (I hope...) generate a `BuildConfiguration.xml`.

That said, I haven't used `ue4 package` for a _plugin_ recently outside a ue4-docker container, so maybe the plugin builder in UAT (or ue4cli) is doing something that isn't done when building a project.

**Comment by CanisHelix** [comment]
@TBBle Interesting, I'll give it another try with all my plugins. I don't have VS2017 on my machine at all (I can't recall if I ever did). It might have been the combination of TargetPlatforms or specific plugins target platforms.

**Comment by TBBle** [comment]
I just checked, and it's [`BuildPlugin` specifically](https://github.com/EpicGames/UnrealEngine/blob/4.26/Engine/Source/Programs/AutomationTool/Scripts/BuildPluginCommand.Automation.cs#L51-L52) that needs `-VS2019`, or it tries to use VS 2017.

So https://github.com/adamrehn/ue4cli/issues/35 shouldn't block _building_ ue4-docker containers with VS2019, unless we are using `ue4cli Package` in a Plugin as part of the process?

**Comment by CanisHelix** [comment]
That's the line, I was just trying to find that again. Just tested it on a fresh machine to confirm it.

adamrehn/ue4cli#35 doesn't block building ue4-docker itself at all. I am using ue4-full images to build plugins that I then use in my CI/CD. If I use a VS2019 ue4-docker, those plugins fail due to that issue.

Sorry for the confusion, and it seems to only affect plugins and not projects.

**Comment by TBBle** [comment]
No worries. We can sort out the ue4 cli problem over in that ticket. I've just had a poke around, and left a comment there.

**Comment by slonopotamus** [comment]
> So adamrehn/ue4cli#35 shouldn't block building ue4-docker containers with VS2019, unless we are using ue4 Package in a Plugin as part of the process?

True, it doesn't prevent ue4-docker from building container images.
