### ISSUE TITLE
The compiler is out of heap space

### ISSUE THREAD

**Issue by herman-rogers** [adamrehn/ue4-docker#19]
First, I just want to say thank you for your work - this is a really tremendous effort and has helped us a lot with out own tooling process.

We're not using your ue4 python package directly but we have followed your docker image layout so we thought maybe you could give us some guidance. Basically, we've gotten all the way to the ue4-minimal image and are attempting to compile the build. When we run:

```dockerfile
RUN .\Engine\Build\BatchFiles\RunUAT.bat BuildGraph -target="Make Installed Build Win64" -script=Engine/Build/InstalledEngineBuild.xml -set:HostPlatformOnly=true
```

We're running into the issue `fatal error c1060, the compiler is out of heap space`. Specifically it's getting to the `[2/10] Compile UnrealHeaderTool Win64` step and that's where it dies with the above error.

I'm assuming this is just a basic config step that we've missed - although not sure where (I think we've pretty much captured everything).

The only caveat is that we're running this inside of a virtual machine which could affect it. However, it's specs are:

- Parallels for Mac
- Windows Enterprise
- 2tb of storage
- 16gb or RAM
- 3 cores

Any idea's for further investigation?

**Comment by adamrehn** [comment]
Hi Boomer, it's good to hear from you again. I'm glad to see that work on Gamebuildr continues to progress.

I've encountered this error quite a few times myself when working with Windows VMs, and it almost always indicates that the Windows pagefile size is too small. (The precompiled headers for the Unreal Engine are pretty massive, so the compiler's memory use spikes like crazy when it builds the PCH files.) The solution is to simply increase the pagefile size.

However, I take it from the dot point "Windows Enterprise" that you're running Windows 10 Enterprise? If so, then that complicates things a little. Windows 10 only supports running containers in Hyper-V isolation mode, [which has a lot of annoying limitations](https://adamrehn.com/docs/ue4-docker/read-these-first/windows-container-primer#hyper-v-isolation-mode-issues), one of which being the inability to control the pagefile size for containers. This limitation is not an issue for containers running in process isolation mode, since they simply use the pagefile settings from the host system, but process isolation mode is only supported under Windows Server. I'd recommend downloading the evaluation version of Windows Server 2019 and installing that in a VM for your local testing. Containers running in process isolation mode run significantly faster than their Hyper-V isolation mode counterparts, and that way your local testing environment will more closely match the sort of production environment you're likely to end up using in the cloud. (Even more so if you opt to install Windows Server without the Desktop Experience.)

In the meantime, I've added [a section discussing this error](https://adamrehn.com/docs/ue4-docker/building-images/troubleshooting-build-issues#building-the-engine-in-a-windows-container-fails-with-the-message-fatal-error-c1060-the-compiler-is-out-of-heap-space) to the *Troubleshooting build issues* page of the ue4-docker documentation to help others who encounter this issue. I'm actually surprised I hadn't documented it already, so my apologies for that oversight.

**Comment by herman-rogers** [comment]
Hey Adam,

Thanks for the quick response - I'll give windows server 2019 a try (I was worried about hyper-v but thought I'd give it a go). And I'll post back here.

As an aside, I'm surprised to see that you know my real name and about Gamebuildr! Sorry if its slipped my mind but have we chatted before (my memory isn't great).

And Gamebuildr is going well - we had to take some time, a lot of time, to professionalize our services but we're getting there at least. Maybe if you guys want we could talk about some beta testing?

**Comment by adamrehn** [comment]
Yes, we chatted once before, albeit very briefly: <https://forums.unrealengine.com/member/1809752-adam-rehn/visitormessage/1471941-visitor-message-from-face_mcgace>. It wasn't your real name that I recognised, but rather your nickname of Boomer, and when I looked at your GitHub profile and saw the Gamebuildr organisation listed there I put two and two together.

Sure thing, that's definitely something I'd be interested in chatting about. I can't see a publicly-listed email address for you anywhere, so would you like to start the conversation by sending an email to me at adam@adamrehn.com?

**Comment by herman-rogers** [comment]
Awesome - I'll shoot you an e-mail. BTW switching to windows server 2019 does resolve the issue.

**Comment by dskvr** [comment]
Is there a suggested size to start at? 

I've been using a 16gb pagefile and still unable to get a windows build while excluding both `debug` and `templates` 

```powershell
$Pagefile = Get-WmiObject Win32_PagefileSetting | Where-Object {$_.name -eq "C:\pagefile.sys"}
$Pagefile.InitialSize = 16384
$Pagefile.MaximumSize = 16384
$Pagefile.put()
```

**Comment by adamrehn** [comment]
@dskvr as I mentioned in [this comment regarding minimum system requirements](https://github.com/adamrehn/ue4-docker/issues/85#issuecomment-641691571), you'll need to do a bit of experimentation to determine the appropriate pagefile size for your system's number of virtual CPU cores (basically the number of threads) and RAM. If your system has around 2GiB of memory per thread (e.g. 8 threads with 16GiB of RAM, 16 threads with 32GiB of RAM, etc.) then I'd recommend starting with a pagefile size equal to 50% of your RAM and then increase it in increments until you find the minimum value that works. If your system only has 1GiB of RAM per thread then I'd start with a pagefile size equal to 100% of your RAM and increment from there.

It's also important to remember that updating the pagefile size requires a system reboot to take effect, so simply changing the values without rebooting the host system (or VM) will have no effect whatsoever.
