### ISSUE TITLE
Configurable Docker registry/namespace

### ISSUE THREAD

**Issue by TBBle** [adamrehn/ue4-docker#21]
Currently, if I want to push the generated images to a private repo, e.g. Amazon ECR, I need to go through and add an extra tag to them, and then push them.

And if I later want to rebuild one of the later images, I need to pull the base images and retag with with `adamrehn/...` or the build script will recreate them from scratch, particularly due to the security token caching issue in ue4-source invalidating the layer cache. (If I understood the [write-up](https://adamrehn.com/articles/building-docker-images-for-unreal-engine-4/#issues-common-to-both-windows-and-linux-containers) correctly).

It seems to my (limited!) Docker expertise that being able to provide an alternative to `adamrehn/` on the `ue4docker build` command line would be useful for automating image builds. A quick search indicates `clean` and `export` would need access to the same things, so perhaps this needs to be slightly-more stable, such as an environment variable?

It's very possible I've got the wrong end of the stick, and am asking for something silly, or that's already solved. If so, I welcome being redirected.

**Comment by adamrehn** [comment]
What you're asking for isn't silly at all, nor is it solved. I've considered adding exactly this option on a number of occasions, since the default names are convenient for me but pretty much nobody else. (The same is also true of the Conan packages generated by [conan-ue4cli](https://github.com/adamrehn/conan-ue4cli), for essentially the same reasons.) In fact, I've actually already [modified the `export` command to support custom tag overrides](https://github.com/adamrehn/ue4-docker/commit/296c10df77fbc7a3b31d9e26ae45397d0746c370) to accommodate the scenario where the built images have been re-tagged and then pulled on another machine that then lacks the original tags.

Since someone has finally made a point of explicitly requesting this, I'll have a think about the best way to implement it to ensure consistency amongst the various commands. The `ue4-build-prerequisites` image will likely retain its current tag to support [pulling the prebuilt version from Docker Hub](https://adamrehn.com/docs/ue4-docker/building-images/advanced-build-options#pulling-a-prebuilt-version-of-the-ue4-build-prerequisites-image), but there's no compelling reason why the other images can't have configurable tag prefixes.

**Comment by TBBle** [comment]
That makes sense to me. I would expect that the ue4-build-prerequisites tag would have to vary by whether it was self-build, or 'pull prebuild from Docker Hub', based on the command line.

If I'm generating it locally, I would expect to push it locally and pull it back later when I need to, consistent with the other images.

**Comment by adamrehn** [comment]
This functionality is now available in ue4-docker version 0.0.30, and is documented here: <https://adamrehn.com/docs/ue4-docker/building-images/advanced-build-options#specifying-a-custom-namespace-for-the-image-tags>
