### ISSUE TITLE
GitHub credentials incorrect

### ISSUE THREAD

**Issue by herman-rogers** [adamrehn/ue4-docker#22]
So just parking fairly common issue, since we can only specify git credentials using our username and password this method will fail if you have 2-factor authentication setup. The simple work around is just to disable 2-factor in your account and the proper fix is to allow using ssh authentication (I don't think at the moment 2-factor for GitHub is enabled via cli but I might be wrong).

**Comment by TBBle** [comment]
You can generate a [Personal Access Token](https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line) to use as a password in this case.

**Comment by adamrehn** [comment]
Thanks @TBBle, it's good to know that the access token option is available for users who have 2FA enabled. I've added [a note about it](https://adamrehn.com/docs/ue4-docker/building-images/advanced-build-options#specifying-git-credentials) to the documentation to make it easier for people to find.

Support for SSH authentication is an interesting option, although it would require a bit of a re-think in terms of how the credential manager is implemented. I'll have a look into how feasible it would be to add an option for it and post a comment here with my findings.

**Comment by herman-rogers** [comment]
Thanks for the tip @TBBle - I'll definitely go down that route in the meantime!

**Comment by TBBle** [comment]
Would the credential manager rethink be easier if it was implemented as a [Credential Helper](https://git-scm.com/docs/api-credentials#_credential_helpers) rather than `SSH_ASKPASS` helper? I'm not totally clear if there's a difference in functionality there, as `SSH_ASKPASS` doesn't appear clearly-documented.

I've been thinking about this myself. My use-case is running on AWS, but if I was running this locally, then I'd like it to read from my SSH Agent in the SSH case.

And at some point, I suspect I'll need to be able to source from Perforce rather than git, which can work off user/pass and off tickets. Perforce is probably distinct-enough that it would need its own credential-managing approach anyway, so that's low-value here.

**Comment by adamrehn** [comment]
@TBBle evidently forwarding of SSH credentials is now possible using experimental build features in the latest builds of Docker: <https://medium.com/@tonistiigi/build-secrets-and-ssh-forwarding-in-docker-18-09-ae8161d066>

Once BuildKit becomes the default build implementation for Docker and support is added for Windows containers, I'll revisit the credential management code in ue4-docker and overhaul it to use the new functionality, which should allow for a far wider variety of authentication mechanisms and source control systems.

**Comment by adamrehn** [comment]
@qhaas yeah, the option to use a local filesystem directory was discussed in #47 and I agree that it could be handy for certain use cases. Support for flexible and pluggable code sources is one of the goals of the big redesign of the project being discussed in #48.

**Comment by fiercefairy** [comment]
It looks like even using no 2 factor or a personal access token fails:

```
Cloning into '/home/ue4/UnrealEngine'...
error: unable to read askpass response from '/tmp/git-credential-helper.sh'
fatal: could not read Username for 'https://github.com': No such device or address
```

**Comment by fiercefairy** [comment]
nevermind. If you have email privacy enabled, you have to use the full masked username + `@users.noreply.github.com` email found in your profile settings as your username

**Comment by adamrehn** [comment]
Strange, I got an email notification for a follow-up comment by @fiercefairy, but it's not showing up here in the actual issue thread. Posting for posterity:

> nevermind. If you have email privacy enabled, you have to use the full masked username + @users.noreply.github.com email found in your profile settings as your username

**Comment by olitazl** [comment]
I got this problem

```
Cloning into '/home/ue4/UnrealEngine'...
error: unable to read askpass response from '/tmp/git-credential-helper.sh'
fatal: could not read Username for 'https://github.com': No such device or address
```

and fixed it by starting `ue4-docker` build. After the start, I did not enter the credentials at first but edit the git-credentials-helper.sh the follows:

```
#!/usr/bin/env bash
git config credential.https://example.com.username myusername
echo "mypassword"
```

After the change hit Enter at the credentials and the docker image will build. I just used it with a one time personal access token.

This helped. The problem seems to be with the server binding delivering the password to the docker image.

**Comment by slonopotamus** [comment]
Note: starting with 13 August, 2021 it will no longer be possible to authenticate using login/password on GitHub. https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/
But we will still be able to use Personal Access Token thing: https://github.com/adamrehn/ue4-docker/issues/22#issuecomment-476968129

**Comment by TBBle** [comment]
Have you tested that you can use your token to clone the repo using `git clone https://github.com/EpicGames/UnrealEngine.git`?

[The docs](https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps) suggest you'd need the `repo` scope, and I don't see a way to say "Read-only access to private repos" there.

**Comment by peters-arrival** [comment]
Yeah thanks for responding. Like you said, it looks like private repos need more aggressive permissions. I changed it to include all "repo" flags and everything is working now.

**Comment by slonopotamus** [comment]
So, what we want from this issue? Password authentication is dead, everyone needs to use PATs now. We _could_ rename all "password" occurences in ue4-docker sources and docs with "access token" (of course via deprecation path with warnings everywhere when you use old term).

**Comment by TBBle** [comment]
That only applies if you're talking to GitHub. Other providers and on-prem can still use passwords, or even not require authentication at all for cloning.

We _could_ check for github.com in the URL and then say "PAT" instead of "password" in the UI, but that seems like more complexity than value...

**Comment by slonopotamus** [comment]
> Other providers and on-prem can still use passwords

Ah, true. So I guess we can just close this?

**Comment by adamrehn** [comment]
As an aside, the naming issue is impossible to avoid when generating Dockerfiles that use BuildKit secrets, since the name of the file for the password or PAT is fixed at generation time. We currently use `password.txt` for the reasons mentioned above, which makes for a fun time when you're documenting how to use the generated Dockerfiles: https://docs.unrealengine.com/4.27/en-US/SharingAndReleasing/Containers/HowTo/BuildingTheLinuxContainerImagesFromSource/#buildingtheimagesforacustomversionoftheengine
