### ISSUE TITLE
Unity Support?

### ISSUE THREAD

**Issue by JohnyHotbody** [adamrehn/ue4-docker#220]
Hi Maintainers and @adamrehn,

Let me first start by saying I really love what this project does. 

However, I was just wondering when `unity-docker` will be coming out as Unity has a much larger user base and is easier to work with.

I hope to hear back soon with positive news!

Many Thank Yous,
Johny Hotbody

**Comment by adamrehn** [comment]
@JohnyHotbody you're in luck, because not only is there already a mature open source project that provides container images for Unity, I also know from personal experience interacting with their community that the maintainers are awesome folks who are super friendly and helpful: https://github.com/game-ci/docker

@webbertakken @GabLeRoux incoming user heading your way! :grinning:
