### ISSUE TITLE
`ue4-build-prerequisites`-only mode

### ISSUE THREAD

**Issue by zorbathut** [adamrehn/ue4-docker#227]
Feature request, with offer of willingness to do work.

I'm working on a CI system built partly on ue4-docker. In our case, the source code is included in a p4 repo which is synced as part of the CI process and should not be built into the Docker image. Basically, we want `build-essentials` and nothing else, everything downstream of that is our problem. In our local branch of ue4-docker we've added a `--no-source` commandline option to suppress building the source image, and I'm happy to give you a pull request for it if you'd like.

But it's pretty dang janky to actually use.

The problem is that the `build` parameters are designed for `ue4-source` to *always* be generated, and therefore it expects, as the first token and without a named `--option`, either a UE4 version or the keyword "custom". Whatever UE4 version you provide is kind of intrinsically incorrect because, y'know, custom from the repo, whereas if you enter "custom" it then demands repo information (which is complicated to enter and also completely ignored because we never generate `ue4-source`). I've bypassed this in my local usage by simply passing in `4.0.0`, which surprisingly works, but, again, pretty dang janky.

It's not clear how to fix this. I think arguably this never should have been a bare argument in the first place, but I've certainly made that mistake in the past myself, and what's done is done. Perhaps this should be a separate build mode entirely (`generate-build-essentials`?) but then you're looking at moving a ton of code to be shared between `build.py` and `generate-build-essentials.py`. Perhaps this *should* be turned into a named argument, with a temporary compatibility mode where it also accepts it as a bare argument. Perhaps the code should just allow it to be skipped if `--no-source` is provided (which is weird in its own right because it means the arguments can't be parsed in order, unless `--no-source` has to be at the beginning, which is *also* weird) or perhaps there should be a special token for "I do not care about this, go away".

I'm happy to spend a little time implementing whatever seems reasonable as long as it's not a massive refactoring. Let me know what you'd prefer, and if you just want `--no-source` in its current format, janky ignored version number and all, I'll turn it into a pull request for ya :)

**Comment by TBBle** [comment]
Without putting too much thought into it, a separate build-mode seems like the least-weird-UX to me.

**Comment by slonopotamus** [comment]
If I understand you correctly, `build-essentials` actually means `ue4-build-prerequisites`. I agree that `--no-source` feels like a hack and a separate command would allow a better UX.

**Comment by TBBle** [comment]
Yeah, perhaps what we want is something like `--target` which defaults to... Hmm. `full` and `engine` are different branches of the pipeline, which would be the default? Maybe `all`? Anyway, `--target` is intended to mirror `docker build`'s support for selecting a target from multiple possible outputs in a single Dockerfile although in our case it's multiple Dockerfiles. (I just now realised, I don't know if `export` produces a single Dockerfile or multiple...)

In theory, if we were working with just one Dockerfile, then there's potential for something like BuildKit to ([someday](https://github.com/moby/buildkit/issues/2627)) optimise the build flow given multiple outputs, although I doubt we'd gain much from it in this project. And that's really a different discussion to this one.

**Comment by zorbathut** [comment]
Oops, yeah, `ue4-build-prerequisites`. Sorry about that! It was a long day.

> Yeah, perhaps what we want is something like --target which defaults to... Hmm. full and engine are different branches of the pipeline, which would be the default?

So, to boil down a few options . . .

----

Currently:

`ue4-docker build 4.27.0`

Maybe-proposed:

`ue4-docker build --ue_version 4.27.0`

(yes, nobody suggested --ue4_version, I'm making it up, feel free to override me)

Which is equivalent to:

`ue4-docker build --ue_version 4.27.0 --target all`

And, hey, let's allow multiple targets, so that's *also* equivalent to:

`ue4-docker build --ue_version 4.27.0 --target full --target engine`

---

Whereas if someone previously did:

`ue4-docker build 4.27.0 --no-full`

now they could do:

`ue4-docker build --ue_version 4.27.0 --target engine`

---

And if someone previously did:

`ue4-docker build 4.0.0 --no-full --no-engine --no-source`

now they could do:

`ue4-docker build --target prerequisites`

(note, no `--ue_version` needed)

---

If I were implementing this, I'd make the unnamed token and `--ue4_version` mutually exclusive; I'd also make `--target` and `--no-*` mutually exclusive. And possibly add a warning for unnamed tokens and `no-*`? Unless you were totally fine just smashing backwards compatibility without warning.

This could also be moved to a new command name, but I think I'd be asking someone else to do the architecture on that because I'd frankly make a royal mess of it, whereas I'm pretty confident messing around with commandline parameters.

Comments? If this looks terrible, tell me :D If it looks not-terrible-but-needs-work, edit as you wish. If it looks good I'll go implement it.

**Comment by zorbathut** [comment]
Ping! Any chance I can get feedback on this? I'd like to get this upstreamed, partly because we're currently relying on a fork and thats ugly, and partly because I actually want to open-source this whole system but I'd hate to release an open-source tool that relies on a fork of another open-source tool.

**Comment by TBBle** [comment]
Well, I definitely like `--target`. ^_^ As for `--ue_version`, my first expectation would be `--ue4-version`, as that's how the other current multi-word options look.

ue4-version is only optional when building build-prerequisites-only, though, and mandatory otherwise, so I'm _uncertain_ about pushing it into a command-line flag rather than positional parameter that is sometimes optional.

I don't think argument parsing order would be a problem either way, since you can't know a positional parameter is missing until all arguments are parsed, by which point you've seen `--target`; I haven't looked at how the argument parser we use handles that though.

All that said, I'm not an active user of the CLI day-to-day (it's run in CI for me these days, and we don't need to generate new images very often anyway) so I may not be the best person to comment on the UX from a recent experience perspective.

**Comment by slonopotamus** [comment]
1. I +1 on `--target`
2. Use `--ue-version` (because we use `-` everywhere else). WRT `4`... Ideally, it should not be anywhere because UE4 is almost history and there's now UE5, but... There's a small problem with ue4-docker _project name_ :D
3. We should keep backward compatibility for unnamed token and `--no-*`. Making them mutually exclusive with `--target` is fine

**Comment by zorbathut** [comment]
> 1. I +1 on `--target`
> 2. Use `--ue-version` (because we use `-` everywhere else). WRT `4`... Ideally, it should not be anywhere because UE4 is almost history and there's now UE5, but... There's a small problem with ue4-docker _project name_ :D
> 3. We should keep backward compatibility for unnamed token and `--no-*`. Making them mutually exclusive with `--target` is fine

Lemme go implement this, then, and I'll provide a pull request at some point soonish :)

(possibly delayed by GDC, sorry if it takes longer than it should)

**Comment by adamrehn** [comment]
Late to the party as always these days, but just adding my thoughts:

- In retrospect, the `--no-*` flags were a poor design choice, and I apologise for inflicting them on everyone. An approach like `--target` makes a great deal more sense, so long as it supports specifying multiple targets (either through multiple instances of the flag as @zorbathut described above, or by accepting a comma-separated list, or even by supporting both and aggregating the results.)

- I probably should've thought about the possibility of a `--ue-version` flag back when I first added support for the `custom` token, given how awkward and confusing that ended up being for most users. The original goal was to provide a way to toggle the repository selection behaviour whilst simultaneously providing a way to specify a name for use in the image tag, but separate flags would have made this far more explicit than shoehorning special semantics into the version field. The impact of this choice is felt quite keenly when generating Dockerfiles using the `-layout` flag, since the version string is still required despite being completely ignored, leading to [confusing invocations accompanied by explanatory comments](https://github.com/EpicGames/UnrealEngine/blob/4.27.2-release/Engine/Extras/Containers/Dockerfiles/linux/generate.sh#L14-L18).

- I concur with @TBBle and @slonopotamus in welcoming these additions, with the requirement that we don't break backwards compatibility for the existing invocation style. Mutual exclusivity between `--target` and the `--no-*` flags also makes sense to me.

- It's worth noting that if you're only interested in the `ue4-build-prerequisites` image then you're no longer beholden to the need to specify credentials, thus eliminating the need for the [awkward credential endpoint functionality](https://adamrehn.com/articles/preview-the-future-of-ue4-docker/#limitations-of-the-current-design) and making it feasible to use `-layout` to generate Dockerfiles for Windows containers just as easily as Linux containers.
  
  Of course, building the prerequisites image under Windows without ue4-docker does mean that you'll need to manually determine the appropriate base image if you want to make use of process isolation mode (or alternatively [script the OS version detection logic](https://github.com/EpicGames/UnrealEngine/blob/5.0/Engine/Extras/Containers/Dockerfiles/windows/build.ps1).) Some day in the future when I actually have free time to work on my FOSS projects again, I should probably create a standalone tool that provides this sort of functionality. At the moment, ue4-docker users get a lot of automatic detection and checking under Windows (along with nice clear warnings/errors that make a lot more sense than some of the stuff that hcsshim spits out) that would be helpful for all developers who are building Windows container images.
