### ISSUE TITLE
Is it possible to reduce the size of ue4-source's final layer?

### ISSUE THREAD

**Issue by TBBle** [adamrehn/ue4-docker#23]
It turns out, AWS's [ECR has a layer-size limit of 10737418240](https://docs.aws.amazon.com/AmazonECR/latest/userguide/service_limits.html), and the final layer of `ue4-source` for 4.21.2 is 24.59GB.

I believe that's just
```Dockerfile
# Run post-clone setup steps
WORKDIR C:\UnrealEngine
RUN Setup.bat
```

Oddly enough, the final layer in `ue4-build-prerequisites` for `ltsc2019` is 14.24GB, but I suspect that the 10GiB limit in AWS is for compressed data, and that 14GB layer compressed well. The 14GB reported by `docker push` might include empty space left after cleaning up, per the comment on the last two steps. I'm not totally sure how Docker works here...

```Dockerfile
# Install the rest of our build prerequisites and clean up afterwards to minimise image size
COPY buildtools-exitcode.py copy.py copy-pdbcopy.py install-prerequisites.bat C:\
RUN C:\install-prerequisites.bat
```

This is a low-value feature request, as long as no other layers grow. I don't *need* to push the ue4-source image at this time (I'm setting up for CI) so it was more about repeatability.

It *might* be worth mentioning in the documentation, but given other limitations on ECR (that 14GB layer in `ue4-build-prerequisites` is present in the other images, but the layer data is not shared across repositories, so I'm paying for that storage four times. >_<)

**Comment by adamrehn** [comment]
Unfortunately there isn't really anything I can do about the size of the Unreal Engine source code itself, or the size of the dependency files that are downloaded by `Setup.bat`. Due to its immense size, the documentation actually [recommends removing the `ue4-source` image at the end of the build process](https://adamrehn.com/docs/ue4-docker/building-images/available-container-images#ue4-source) to free up disk space. The unspoken expectation is that anyone running ue4-docker within a CI context will start from a fresh slate each time, either building or [pulling the prebuilt version](https://adamrehn.com/docs/ue4-docker/building-images/advanced-build-options#pulling-a-prebuilt-version-of-the-ue4-build-prerequisites-image) of the `ue4-build-prerequisites` image and building all subsequent images from source.

It's worth noting that Docker Hub's paid plans charge on a per-repository basis rather than a filesize basis, which is far better suited to massive container images like those produced by ue4-docker. I also know for a fact that Docker Hub shares layer data between repositories, and although I'm not sure about size limits on individual layers, I do know that there are no overall size limits for container images. I realise that storing images on Docker Hub isn't ideal from a performance perspective if you need to be pulling them from within an AWS availability zone, but from a purely storage standpoint it's definitely the most cost-effective option.

**Comment by TBBle** [comment]
The Docker Hub suggestion is good, although I guess that means I'm paying traffic costs instead. I also haven't looked at what other cloud providers use (I just happened to have AWS at-hand), so at this experimentation/discovery stage, storage cost is not a driver.

Hopefully the person who *does* need to track costs isn't reading my Github activity log...

The main reasons I'm keen to push and keep things are:
* I understood ue4-source was likely to change underneath me for auth-token reasons, and would invalidate caches on recreation.
* The whole build-pipe took 18 hours, and I'd really like to avoid having to redo that. ^_^ This one might be on my selection of AWS instance, I probably made a poor choice (t3.xlarge to get 16GB of RAM, since the 8GB version kept Bugchecking during the build)

Depending on how we go, we may be pushing the ue4-source package from elsewhere, particularly if-and-when we have projects that're using project-specific UE4 branches, or even for builds from Unreal's own Perforce, e.g., for console targets. That's however for later stages, once I've proved this part workable for in-house development and playtest iteration.

I'll close this ticket off for now, as it's pretty-much what I expected. If it proves problematic, I might look at the python scripts that already hack Setup.bat, and see if I can do anything to auto-split it into multiple layers or something.

**Comment by adamrehn** [comment]
Just a quick follow-up for posterity in case anyone else reads this thread later:

- Yes, the randomly-generated security token used by the credential endpoint will indeed result in unique layer hashes for each build of the `ue4-source` image, invalidating Docker's build cache. Unfortunately I've yet to find a satisfactory workaround for this, which is why I've done my best to isolate the effects to that one image.

- 18 hours is a startlingly long time for a full build of the container images produced by ue4-docker. I can see from the AWS documentation that a t3.xlarge instance has 4 vCPUs to accompany that 16GiB of RAM. I know from experience that a full build of the Windows versions of the images (which take longer to build than the Linux versions) on a physical machine with similar specs takes less than 10 hours (that's for the entire set of images, i.e. build prereqs, `-source`, `-engine`, `-minimal`, and `-full`.) The only relevant factors not stated are disk and network specs, but network can probably be ruled out since an AWS datacentre is pretty much guaranteed to have a better network connection than my residential 100Mbps NBN. Assuming an SSD was used for the instance's root volume and the instance wasn't a [spot instance](https://aws.amazon.com/ec2/spot/) that got interrupted during the build, I'm at somewhat of a loss as to why the build would've taken so long.

**Comment by TBBle** [comment]
My suspicion is that "t3" doesn't get all 4 vCPUs all the time due to the bursting behaviour. Next time I do this, I'll do it on an m5.large or m4.large, to rule that out. Most of that 18 hours was spent building ue4-minimal, as I recall, as I'd already gotten prereqs built, and ue4-source logged 44 minutes to complete.
