### ISSUE TITLE
unable to determine Windows Server Core base image tag from host system

### ISSUE THREAD

**Issue by alexgeek** [adamrehn/ue4-docker#232]
Output of the `ue4-docker info` command:

```
ue4-docker info
ue4-docker version:         0.0.96 (latest available version is 0.0.96)
Operating system:           Windows 10 Pro (Build 19044.1620)
Docker daemon version:      20.10.13
NVIDIA Docker supported:    No
Maximum image size:         800GB
Available disk space:       702.77 GiB
Total system memory:        63.93 GiB physical, 73.43 GiB virtual
CPU:                        8 physical, 16 logical (AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD)
```

Additional details:

- Are you accessing the network through a proxy server? No

Hi,

I've updated my machine due to the EOL of 20H2 (https://github.com/adamrehn/ue4-docker/issues/216#issuecomment-1079669417).
Now when trying to build I get:

```
[ue4-docker build] Error: unable to determine Windows Server Core base image tag from host system. Specify it explicitly using -basetag command-line flag
```

If specify `-basetag 20H2` then I get:

```
hcsshim::CreateComputeSystem 430289b44ed2bdd85bc91f792e55a13e59f1a578e3f55874d18029d4940dc0e5: The container operating system does not match the host operating system.
[ue4-docker build] Error: failed to build image "adamrehn/ue4-build-prerequisites:20H2-vs2017".
```

I can't see much in the docs related to this. It looks like in other issues most of you are building with ltsc, does this still work for Win 10 Pro?

Thanks

**Comment by slonopotamus** [comment]
I wonder why we're not switching automatically to hyper-v isolation on 21H2 host + 20H2 guest =/

**Comment by adamrehn** [comment]
So, having a look through the code to refresh my memory, the [isolation mode selection logic](https://github.com/adamrehn/ue4-docker/blob/47c81a4480fbd06b5cda425ff214bcb628c0083b/ue4docker/infrastructure/BuildConfiguration.py#L477-L485) will use process isolation mode where it can, and if it can't then it will fall back to the **system's default isolation mode** rather than explicitly selecting Hyper-V isolation mode. This seems like an oversight on my part, since we know we need Hyper-V isolation mode in the case of mismatched kernel versions and we can't safely rely on the system default given that it not only varies between client and server versions of Windows but can also be modified by the user (which I'm guessing might be the case for @alexgeek?)

**Comment by adamrehn** [comment]
@alexgeek yes, the base tag should default to `ltsc2022` under Windows 11 host systems. I'll add the relevant build number to the lookup table now.
