### ISSUE TITLE
ERROR: Couldn't find target rules file for target 'UE4Editor' in rules assembly 'UE5Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

### ISSUE THREAD

**Issue by rawatravi** [adamrehn/ue4-docker#249]
[ue4-docker build] Error: failed to build image "adamrehn/ue4-engine:5.0.0-ltsc2019-vs2019".

```
Step 1/8 : ARG NAMESPACE
Step 2/8 : ARG TAG
Step 3/8 : ARG PREREQS_TAG
Step 4/8 : FROM ${NAMESPACE}/ue4-source:${TAG}-${PREREQS_TAG}
 ---> fe420154cb8b
Step 5/8 : RUN GenerateProjectFiles.bat && echo. && echo.RUN directive complete. Docker will now commit the filesystem layer to disk. && echo.Note that for large filesystem layers this can take quite some time. && echo.Performing filesystem layer commit... && echo.
 ---> Using cache
 ---> efa6bdfc160a
Step 6/8 : RUN .\Engine\Build\BatchFiles\Build.bat UE4Editor Win64 Development -WaitMutex && echo. && echo.RUN directive complete. Docker will now commit the filesystem layer to disk. && echo.Note that for large filesystem layers this can take quite some time. && echo.Performing filesystem layer commit... && echo.
 ---> Running in 4ec92b61447e
Using bundled DotNet SDK
Log file: C:\UnrealEngine\Engine\Programs\UnrealBuildTool\Log.txt
Using 'git status' to determine working set for adaptive non-unity build (C:\UnrealEngine).
Creating makefile for UE4Editor (no existing makefile)
ERROR: Couldn't find target rules file for target 'UE4Editor' in rules assembly 'UE5Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
       Location: C:\UnrealEngine\Engine\Intermediate\Build\BuildRules\UE5Rules.dll
       Target rules found:
The command 'cmd /S /C .\Engine\Build\BatchFiles\Build.bat UE4Editor Win64 Development -WaitMutex && echo. && echo.RUN directive complete. Docker will now commit the filesystem layer to disk. && echo.Note that for large filesystem layers this can take quite some time. && echo.Performing filesystem layer commit... && echo.' returned a non-zero code: 6
[ue4-docker build] Error: failed to build image "adamrehn/ue4-engine:5.0.0-ltsc2019-vs2019".
```

 command : ue4-docker build --ue-version 5.0.0 --visual-studio 2019 using virtual machine windows server 2019

**Comment by slonopotamus** [comment]
Please, use `--no-engine`, or, better `--target=full`/`--target=minimal`. ue4-engine image is currently broken for UE5.

**Comment by slonopotamus** [comment]
I really, really wonder if anyone needs ue4-engine image at all...

**Comment by jonpas** [comment]
> I really, really wonder if anyone needs ue4-engine image at all...

Even if someone does, most documented use-cases don't have a use for it. I think it should be disabled by default.

`--target=full` should be the default. I think it's better than just `--target=minimal` because it's a very quick to build on top of `full` and quite useful.

**Comment by rawatravi** [comment]
--target=full works for me 👍

**Comment by slonopotamus** [comment]
I'll reopen this so we do not forget to change default target to `full`.

**Comment by ki11roy** [comment]
> I really, really wonder if anyone needs ue4-engine image at all...

Good point, maybe it is a good time for removing it (instead of fixing).

**Comment by philip-klein** [comment]
Although there may not seem any use in the engine image, there is actually a functionality difference between an installed build and a source build of unreal.

My team requires a source build so that unreal can package individual plugins. This feature breaks with an installed build. Packaging a plugin allows you to send downstream developers packaged versions of your plugin instead of the source code. We use CI to verify this process on every merge in all of our plugins.

If we loose the ability to use the engine image, we will be forced to maintain our own dockerfiles and build process for these images.

I know it's a lot to ask, but it would mean a lot if you could continue to support the engine image going forward.

**Comment by philip-klein** [comment]
@slonopotamus 
Although there may not seem any use in the engine image, there is actually a functionality difference between an installed build and a source build of unreal.

My team requires a source build so that unreal can package individual plugins. This feature breaks with an installed build. Packaging a plugin allows you to send downstream developers packaged versions of your plugin instead of the source code. We use CI to verify this process on every merge in all of our plugins.

If we loose the ability to use the engine image, we will be forced to maintain our own dockerfiles and build process for these images.

I know it's a lot to ask, but it would mean a lot if you could continue to support the engine image going forward.

**Comment by philip-klein** [comment]
I'm continuing the discussion in #313 since this issue is closed
