### ISSUE TITLE
Question: Support for mounting Engine source from host?

### ISSUE THREAD

**Issue by jlsalmon** [adamrehn/ue4-docker#251]
Hi folks,

Thanks for the great work with this library, it's really transformed our internal CI/CD pipelines for UE. I was wondering whether it might make sense to add support for mounting the Engine source directory from the host, rather than cloning it or `COPY`'ing it into the build container? I'm currently using the copy method, and it takes up a really large chunk of execution time. I figured that since the source is discarded from the minimal image anyway, it might be acceptable to do this.

Any thoughts on this or am I missing something obvious here? Cheers!

**Comment by TBBle** [comment]
Without buildkit, it's not possible as `docker build` doesn't support mounts during builds. So that rules out Windows entirely for now.

On Linux, we've recently switched to requiring BuildKit on Linux, so it would be _possible_ to use [`RUN --mount=type=bind`](https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/syntax.md#run---mounttypebind-the-default-mount-type), but will require some plumbing. I don't have the source in front of me to see _how much_ plumbing, so it might be feasible as-is, or might be something that should be tackled by the (somewhat delayed) infrastructure redesign in #48.

#48 was originally spawned by proposed `COPY` support (in #47) although it's since been implemented for the 'exported Dockerfile' case. If that case works for you, then this might be feasible to add in a similar way, but it'd be somewhat more intrusive due to needing to modify every `RUN` line in ue4-minimal's `builder` image, 

There's also the risk that such mounts are read-only in the container (or at least, writes to them are discarded) and I suspect the UE4 code-base does not do a good job of separating source from outputs, so there's a reasonable chance it won't work anyway.

And the ue4-source Dockerfile does a fair bit of patching of the source (that's basically _all_ it does when using `source_mode=copy`; if the `disable_all_patches` flag is also specified, ue4-docker condenses to _one_ `COPY` line.)

So my initial poking around suggests that it'd be quite hard to use a build-time bind-mount unless we could combine the patching (or skip or pre-apply them), the build, and the copying of resulting binaries somewhere else in the image that isn't lost at the end of the step into a single `RUN`. And that'd be a significant change from what we have now.

**Comment by jlsalmon** [comment]
Ah yes, I forgot that BuildKit isn't supported on Windows, that's a shame. In that case, I guess it would seem awkward to try to introduce logic to achieve this _only_for linux. 

Thanks for the prompt and detailed response @TBBle 👍
