### ISSUE TITLE
Ability to detect if build will succeed based on free disk space?

### ISSUE THREAD

**Issue by alexgeek** [adamrehn/ue4-docker#254]
Hi,

I ran a build for 4.26.2 yesterday which took all day and failed at one of the last steps because it didn't have enough disk space. The machine actually has 1589.71GB free so it's likely the amount allocated in docker settings rather than actually total disk space left. 

I already had an image for 4.27.2 built on the machine so I'm guessing that was using part of what it has allocated. Do you think there's a preflight check that could be added to ensure there's enough a space before building? May save a lot of time.

Thanks

**Comment by TBBle** [comment]
The container-space allocation (i.e the thing that runs out of space even if there's room on the hosting drive) is limiting the container's scratch space (free space inside the container) per-container-run, so it's not affected by existing images. They would consume actual space on the drive.

If your configuration (per `ue4-docker info`) was large-enough for 4.27, I'm surprised it's not large enough for 4.26, as it always seemed to me that UE4 only _grew_ in size over time.

One of the issues with detecting this space is that we can't precisely determine from the config what the scratch size will be, because it's possible to configure it in ways that ue4-docker can't see, so we just guess from the dockerd.json, which is the same place we (and MS) document to change that size. But it can be affected by, e.g. dockerd command line, or having not restarted the Docker daemon since changing the config.

The only surefire way to know how large the scratch space will be is to actually run a container and use `dir C:` or similar to find out how much space it was given. We could perhaps teach `ue4-docker info` to do that, or add a `ue4-docker diagnostics` command that can check? However, the required space can vary by the parameters used to build; we document that 400GB is large enough, but it doesn't hurt to go higher unless you're worried about a container build going rouge and consuming all your disk space. (You need to have 3x the used space in a container layer free while it's finishing writing the layer back to storage but that's unrelated to the scratch size, and you'd see that with e.g., `--monitor` showing you running out of drive space).

**Comment by alexgeek** [comment]
> The container-space allocation (i.e the thing that runs out of space even if there's room on the hosting drive) is limiting the container's scratch space (free space inside the container) per-container-run, so it's not affected by existing images. They would consume actual space on the drive.
> 
> If your configuration (per `ue4-docker info`) was large-enough for 4.27, I'm surprised it's not large enough for 4.26, as it always seemed to me that UE4 only _grew_ in size over time.
> 
> One of the issues with detecting this space is that we can't precisely determine from the config what the scratch size will be, because it's possible to configure it in ways that ue4-docker can't see, so we just guess from the dockerd.json, which is the same place we (and MS) document to change that size. But it can be affected by, e.g. dockerd command line, or having not restarted the Docker daemon since changing the config.
> 
> The only surefire way to know how large the scratch space will be is to actually run a container and use `dir C:` or similar to find out how much space it was given. We could perhaps teach `ue4-docker info` to do that, or add a `ue4-docker diagnostics` command that can check? However, the required space can vary by the parameters used to build; we document that 400GB is large enough, but it doesn't hurt to go higher unless you're worried about a container build going rouge and consuming all your disk space. (You need to have 3x the used space in a container layer free while it's finishing writing the layer back to storage but that's unrelated to the scratch size, and you'd see that with e.g., `--monitor` showing you running out of drive space).
> 
> Umm, I should check: This is Windows, right? I assume so, because Linux containers (except dm-snapshot, which is AFAIK unsuported) doesn't have the concept of scratch-space allocation like this, it can use whatever space is free on the hosting drive.

I see, a lot more complicated than I imagined. A diagnostic sounds like the most sensible approach but still fiddly as you said.

Yes this is Windows, I found that I forgot `--exclude debug` so I assume that's why it was running out of space even with 800GB allocated. Though I have no idea how much you need to allocate for a debug build to complete?

**Comment by slonopotamus** [comment]
Are you sure you're not hitting #99? Does `ue4-docker diagnostics 20gig` pass for you? If not, see https://github.com/adamrehn/ue4-docker/issues/99#issuecomment-1079702817.

**Comment by slonopotamus** [comment]
Yes, you're hitting #99.

**Comment by TBBle** [comment]
Okay, closing in favour of https://github.com/adamrehn/ue4-docker/issues/99#issuecomment-1079702817, as not using `--exclude debug` is a known trigger for that one, and the alternative Docker daemon build in that comment should fix it.
