### ISSUE TITLE
Unable to build 5.1.0 on Windows Server 2019

### ISSUE THREAD

**Issue by CanisHelix** [adamrehn/ue4-docker#278]
Output of the `ue4-docker info` command:

```
ue4-docker version:         0.0.101 (latest available version is 0.0.101)
Operating system:           Windows Server 2019 Standard (Build 17763.1935)
Docker daemon version:      master-dockerproject-2022-02-28
NVIDIA Docker supported:    No
Maximum image size:         1024GB
Available disk space:       1.44 TiB
Total system memory:        16 GiB physical, 31 GiB virtual
CPU:                        9 physical, 18 logical (Intel64 Family 6 Model 85 Stepping 4, GenuineIntel)
```

Additional details:

- Are you accessing the network through a proxy server? **No**

```
$env:UE4DOCKER_TAG_NAMESPACE="administratum.imperium.iceseed.com"; ue4-docker build 5.1.0 --visual-studio=2022 --exclude debug --exclude templates --exclude ddc --monitor --opt disable-labels --opt enable-dso-patch --opt buildgraph-args="-set:WithClient=true -set:WithServer=true"
```

I've been using this command on this machine for a long time now. I updated to 0.0.101 and ran my usual command above. Other than changing up to VS2022 from VS2019. But even specifying 2019 fails with the same error.

This resulted very quickly in the following error:

```
[ue4-docker build] Warning: You're building Unreal Engine 5
[ue4-docker build] Warning: You might hit Docker 20GiB COPY bug
[ue4-docker build] Warning: Make sure that `ue4-docker diagnostics 20gig` passes
[ue4-docker build] Warning: See https://github.com/adamrehn/ue4-docker/issues/99#issuecomment-1079702817 for details and workarounds
c:\python39\lib\site-packages\pkg_resources\__init__.py:123: PkgResourcesDeprecationWarning: master-dockerproject-2022-02-28 is an invalid version and will not be supported in a future release
  warnings.warn(
[ue4-docker build] COMMAND-LINE INVOCATION:
[ue4-docker build] ['ue4-docker', '5.1.0', '--visual-studio=2022', '--exclude', 'debug', '--exclude', 'templates', '--exclude', 'ddc', '--monitor', '--opt', 'disable-labels', '--opt', 'enable-dso-patch', '--opt', 'buildgraph-args=-set:WithClient=true -set:WithServer=true', '-username', 'CanisHelix', '-password', '*******']

[ue4-docker build] UNREAL ENGINE VERSION SETTINGS:
[ue4-docker build] Custom build:  No
[ue4-docker build] Release:       5.1.0
[ue4-docker build] Repository:    https://github.com/EpicGames/UnrealEngine.git
[ue4-docker build] Branch/tag:    5.1.0-release

[ue4-docker build] ADVANCED CONFIGURATION OPTIONS:
[ue4-docker build] buildgraph_args: "-set:WithClient=true -set:WithServer=true -set:VS2022=true"
[ue4-docker build] disable_labels: true
[ue4-docker build] enable_dso_patch: true
[ue4-docker build] excluded_components: {"ddc": true, "debug": true, "templates": true}

[ue4-docker build] WINDOWS CONTAINER SETTINGS
[ue4-docker build] Isolation mode:               hyperv
[ue4-docker build] Base OS image:                mcr.microsoft.com/windows/servercore:ltsc2019
[ue4-docker build] Dll source image:             mcr.microsoft.com/windows:1809
[ue4-docker build] Host OS:                      Windows Server 2019 Standard (Build 17763.1935)
[ue4-docker build] Memory limit:                 10.00GB
[ue4-docker build] Detected max image size:      1024GB
[ue4-docker build] Visual Studio:                2022
[ue4-docker build] GENERAL SETTINGS
[ue4-docker build] Build targets: build-prerequisites full minimal source
[ue4-docker build] Changelist override: 23058290
[ue4-docker build] Excluding the following Engine components:
[ue4-docker build] - Debug symbols
[ue4-docker build] - Derived Data Cache (DDC)
[ue4-docker build] - Template projects and samples

Retrieving the Git credentials that will be used to clone the UE4 repo
Using username specified via `-username` command-line argument.
Using password specified via `-password` command-line argument.


[ue4-docker build] Building image "administratum.imperium.iceseed.com/ue4-build-prerequisites:ltsc2019-vs2022"...
Sending build context to Docker daemon  17.45kB
Step 1/16 : ARG BASEIMAGE
Step 2/16 : ARG DLLSRCIMAGE
Step 3/16 : FROM ${DLLSRCIMAGE} as dlls
 ---> 1773691e1aba
Step 4/16 : FROM ${BASEIMAGE} as deduplication
 ---> c703d4d60533
Step 5/16 : SHELL ["cmd", "/S", "/C"]
 ---> Using cache
 ---> ea2cc984e28a
Step 6/16 : COPY --from=dlls     C:\Windows\System32\avicap32.dll     C:\Windows\System32\avifil32.dll     C:\Windows\System32\avrt.dll     C:\Windows\System32\d3d10warp.dll     C:\Windows\System32\D3DSCache.dll     C:\Windows\System32\dsound.dll     C:\Windows\System32\dxva2.dll     C:\Windows\System32\glu32.dll     C:\Windows\System32\ksuser.dll     C:\Windows\System32\mf.dll     C:\Windows\System32\mfcore.dll     C:\Windows\System32\mfplat.dll     C:\Windows\System32\mfplay.dll     C:\Windows\System32\mfreadwrite.dll     C:\Windows\System32\msacm32.dll     C:\Windows\System32\msdmo.dll     C:\Windows\System32\msvfw32.dll     C:\Windows\System32\opengl32.dll     C:\Windows\System32\ResampleDMO.dll     C:\Windows\System32\ResourcePolicyClient.dll     C:\GatheredDLLs\
 ---> Using cache
 ---> 741d4ba7f921
Step 7/16 : COPY remove-duplicate-dlls.ps1 C:\remove-duplicate-dlls.ps1
 ---> Using cache
 ---> 40ccbcc42c46
Step 8/16 : RUN powershell -ExecutionPolicy Bypass -File C:\remove-duplicate-dlls.ps1 && echo. && echo.RUN directive complete. Docker will now commit the filesystem layer to disk. && echo.Note that for large filesystem layers this can take quite some time. && echo.Performing filesystem layer commit... && echo.
 ---> Running in aefd483fdcc1
[ue4-docker build] [2022-11-18 02:41:35] [Available disk: 1.44 TiB] [Available memory: 14.60 GiB physical, 29.70 GiB virtual] [CPU usage: 0.00%]
hcs::CreateComputeSystem aefd483fdcc1ede7e4db921d400ded3287bdedcd7ec5f15b27bc4a880ff6bfbc: The request is not supported.
[ue4-docker build] Error: failed to build image "administratum.imperium.iceseed.com/ue4-build-prerequisites:ltsc2019-vs2022".
```

**Comment by CanisHelix** [comment]
Updating to SteveDore via https://github.com/adamrehn/ue4-docker/issues/99#issuecomment-1079702817 despite having a updated to work around the size limits via https://github.com/adamrehn/ue4-docker/issues/225#issuecomment-1054893145 already.

Stevedore is now an enforced requirement?

**Comment by slonopotamus** [comment]
> Stevedore is now an enforced requirement?

No, it isn't. It is just one of ways to quickly get Docker that has mentioned bug fixed.

**Comment by TBBle** [comment]
It's _possible_ that if you enable the [Containerd Image Store beta feature](https://docs.docker.com/desktop/containerd/) in Docker Desktop, that'll use a new-enough build of Docker Engine under the hood.

The original report shows `master-dockerproject-2022-02-28` which would have contained the fix for #99, as this would have been a build from what's now the 22.06 beta branch. However, the error shown was _not_ the #99 error. The #99 error comes from a `COPY` step, and the other size-related issue comes from the _end_ of a `RUN` after the container execution has finished.

```
hcs::CreateComputeSystem aefd483fdcc1ede7e4db921d400ded3287bdedcd7ec5f15b27bc4a880ff6bfbc: The request is not supported.
```

This suggests something else had gone wrong, as the _container creation_ failed. It's the first `RUN` in the build shown, so it's also the first time a container was created.

Since switching to Stevedore (which AFAIR is the 20.06 stable branch with relevant fix or fixes backported) fixed the issue, I guess either you hit a bug in Docker (which hopefully has since been fixed) or there was a temporary issue in your environment, perhaps cleared by a reboot or some other action during the install of Stevedore.

I note that this was HyperV isolation, so it's possible that HyperV isolation was temporarily broken in Docker Engine in February; it wouldn't be the first time.

**Comment by CanisHelix** [comment]
This VM has been building docker images since 4.27, it's really only for building these images. Not a big deal as installing Stevedore did fix it, but it's here now in case someone else does hit the same error, slim chances though.

I probably should update to Windows Server 2022 Core at some point along with the CI farm's runners too.

```
mcr.microsoft.com/windows                                    1809                    1773691e1aba   9 months ago   15.1GB
mcr.microsoft.com/windows/servercore                         ltsc2019                c703d4d60533   9 months ago   5.75GB
```

I don't believe it picked up a new base image as it tried to use the same one's from 5.0.x and 4.27.x builds on the same VM.

**Comment by TBBle** [comment]
That's weird because at this point in the process, it doesn't know what version of UE is being built, it's still building the common prerequisites image. So I don't understand how 4.27.x and 5.0.x builds could have been working but this one failed.

I _think_ (but haven't checked in a while) it should have re-used your existing prerequisites image from a 5.0.x build (assuming the same `ltsc2019-vs2022` setup), rather than trying to build a new version of the same image.

**Comment by slonopotamus** [comment]
> it's still building the common prerequisites image

Buuut! 

> changing up to VS2022 from VS2019

We have separate ue4-build-prerequisites tag for each VS version.

Anyway, as of today, no engine version can build with VS2022 unless you apply a bunch of hacks. And we don't have those hacks in ue4-docker.

**Comment by TBBle** [comment]
> changing up to VS2022 from VS2019

Oh, I missed that, that explains why it was building a new prereqs image from scratch. Anyway, it's somewhat beside the point for the issue seen here, because the VS version chosen shouldn't affect this execution.

Unfortunately, this error is fairly generic, and suggests _something_ in the container description Docker passed to HCS was rejected, but there's no real way to tell what specifically was wrong, and ue4-docker isn't doing anything that should be able to cause that to happen anyway.

So I'm still leaning towards some fault in that Docker daemon build, that somehow wasn't triggered until now.

I'd be curious to know if the Stevedore-based attempt that worked was also using hyperv isolation. But it's only curiosity at this point.
