### ISSUE TITLE
Allow for Custom Engine

### ISSUE THREAD

**Issue by Mulugruntz** [adamrehn/ue4-docker#3]
Hi Adam!

First, I'd like to say thanks for this huge piece of work! I haven't tested it yet but it looks pretty promising to me :-) 

There's just one small corner-case (I think, but I might find more later XD) missing imho, it's when you have a custom UE4 build.

In that case, we might need an extra `ARG` consumed here https://github.com/adamrehn/ue4-docker/blob/master/dockerfiles/ue4-source/windows/Dockerfile#L22

I suggest `GIT_REPOSITORY`.

What's your opinion on that?

**Comment by adamrehn** [comment]
Hi Sam,

Thanks for suggesting this! This is certainly a use case worth supporting, since it allows developers to perform CI with their own in-house Engine customisations, or simply with code that has been submitted to Epic as a pull request but not yet merged.

Changing the URL for the Git repository alone is only half of the picture, since the user will ideally also need to be able to specify a particular branch to be cloned. This way the branch for a specific modification can be targeted, which provides maximum flexibility and also meshes well with the use case of targeting code that has been submitted as a pull request to the main UE4 GitHub repository.

However, the ability to use an arbitrary branch rather than always using the tag for a specific release will remove the synchronisation that currently exists between the user-specified Engine version number and the actual version being built. This will render the version-based checks inside the build script (which enable or disable certain images) completely ineffective. In order to support custom repositories and branches, these version checks first need to be migrated inside the Dockerfiles, so that they can detect the correct Engine version from inside the containers as they are being built. I've been contemplating doing exactly this for some time (since this will allow me to streamline everything far better than the current checks) and I now have the perfect catalyst for doing so.

I will implement the prerequisite changes and then take a look at your pull request (#4) once they are in place.

**Comment by adamrehn** [comment]
This functionality has now been implemented in commit 7f682cd.
