### ISSUE TITLE
Add option to delete useless folders 

### ISSUE THREAD

**Issue by Ludea** [adamrehn/ue4-docker#32]
It could be interesting to delete Templates, Samples and FeaturePacks folder into minimal container. 

For continous integration, user comes with his project, and no need these folder. 

And and the size of the container is less large

Edit : pass argument to Setup.bat / Setup.sh can delete useless platform like TVOs, Xbox, mac, Android. 
Do `--no-xbox` for example, could be interesting to delete no targeted platforms
Here a link with some explanation https://forums.unrealengine.com/development-discussion/engine-source-github/25735-tutorial-how-to-use-setup-bat-and-how-to-reduce-download-size

**Comment by adamrehn** [comment]
Although these directories cannot be deleted by default because they are required by [other use cases](https://unrealcontainers.com/docs/use-cases/), it might be possible to add an option to allow the user to request their removal. The primary obstacle to this is the need to correctly edit the Engine's file manifests, since removal of any file listed in a manifest will result in errors when attempting to use the Engine to package projects. I will look into the feasibility of this and report my findings here.

My understanding is that passing arguments to `Setup.bat` and `Setup.sh` is not necessary under recent versions of UE4, since the files for optional target platforms are excluded by default. That being said, it's possible that the files for HTML5 are being downloaded despite the fact that the container images don't currently support building or packaging for that target platform, so I'll have a look into it and see if there's any noticeable size savings to be had there.

**Comment by adamrehn** [comment]
This functionality is now available in ue4-docker version 0.0.30, and is documented here: <https://adamrehn.com/docs/ue4-docker/building-images/advanced-build-options#excluding-engine-components-to-reduce-the-final-image-size>

It turns out that the directories in question are not included in any of the Engine manifest files, so they can be removed safely and without fuss. It is also not necessary to add the platform exclusion arguments to `Setup.bat` and `Setup.sh`, since the inclusion of the `-set:HostPlatformOnly=true` flag when creating the Installed Build ensures the exclusion of any files for other target platforms.
