### ISSUE TITLE
failed to build ue4-full 4.22

### ISSUE THREAD

**Issue by hxdnshx** [adamrehn/ue4-docker#33]
Output of the `ue4-docker info` command:
ue4-docker version:         0.0.29
Operating system:           Linux (Ubuntu 16.04.5 LTS, 4.15.0-47-generic)
Docker daemon version:      18.09.3
NVIDIA Docker supported:    Yes
Maximum image size:         No limit detected
Total system memory:        31.38 GiB
Number of processors:       4 physical, 8 logical

Removing intermediate container 5db555ef2102
 ---> 76dad35e05a7
Step 9/27 : RUN ue4 conan generate && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''
 ---> Running in 03a0b24c2a24
Using user-specified engine root: /home/ue4/UnrealEngine
Removing the "ue4" Conan profile if it already exists...
Removing any previous versions of profile base packages...
Traceback (most recent call last):
  File "/usr/local/bin/ue4", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/ue4cli/cli.py", line 216, in main
    SUPPORTED_COMMANDS[command]['action'](manager, args)
  File "/usr/local/lib/python3.5/dist-packages/conan_ue4cli/main.py", line 34, in main
    SUBCOMMANDS[subcommand]['function'](manager, args[1:])
  File "/usr/local/lib/python3.5/dist-packages/conan_ue4cli/generate.py", line 152, in generate
    clang = _detectClang(manager)
  File "/usr/local/lib/python3.5/dist-packages/conan_ue4cli/generate.py", line 68, in _detectClang
    versions.append((bundledClang[0], bundledClang[0] + '++', _getClangVersion(bundledClang[0] + '++')))
  File "/usr/local/lib/python3.5/dist-packages/conan_ue4cli/generate.py", line 44, in _getClangVersion
    return parse_version(matches[1].replace('-', '.'))
TypeError: '_sre.SRE_Match' object is not subscriptable
The command '/bin/sh -c ue4 conan generate && echo '' && echo 'RUN directive complete. Docker will now commit the filesystem layer to disk.' && echo 'Note that for large filesystem layers this can take quite some time.' && echo 'Performing filesystem layer commit...' && echo ''' returned a non-zero code: 1
[ue4-docker build] Error: failed to build image "adamrehn/ue4-full:4.22.0-opengl".

```

the following file is complete log.
[buildlog222.txt](https://github.com/adamrehn/ue4-docker/files/3152819/buildlog222.txt)

**Comment by hxdnshx** [comment]
Addition:
python3 --version
Python 3.7.3

**Comment by adamrehn** [comment]
That error indicates that you are using Python 3.5 or older, since support for the subscript operator [was added to regular expression match objects in Python 3.6](https://docs.python.org/3/library/re.html#re.Match.__getitem__). The use of the subscript operator was an oversight on my behalf, since conan-ue4cli does indeed support Python 3.5, and I have [fixed this problem](https://github.com/adamrehn/conan-ue4cli/commit/05f855d2a72a43ae27a60fba9bd497c3b956cae7) in conan-ue4cli version 0.0.13. Rebuilding the `ue4-full` image should use the updated version and build successfully.

Out of curiosity, what base image are you using? Or more to the point, what modifications have you made to the ue4-docker Dockerfiles? I can see from your build log that you're definitely using a modified version:

- You're building the `opengl` variant of the images, but the output of `apt-get update` clearly shows the NVIDIA CUDA package repositories (which are usually only included in the `cudagl` variant), as well as other package sources that are not included in any of the variants that can be built using an unmodified version of ue4-docker.

- You're copying the Unreal Engine source code from the host system rather than cloning it from GitHub, a step which is ordinarily hard-coded into the Dockerfiles. (The inclusion of the `v13_clang-7.0.1-centos7` toolchain and the fact that it was later copied into the Installed Build indicates that it is indeed version 4.22.0 of the Engine, since that toolchain was introduced in 4.22 and is automatically copied into Installed Builds since 4.22.1, resulting in a no-op for the ue4-docker custom copy step that is accompanied by output stating that the toolchain already exists.)

It is worth noting that Unreal Engine 4.22.0 contains a bug that prevents Installed Builds of the Engine from being able to build projects under Linux, as mentioned in [the release notes for version 4.22.1](https://forums.unrealengine.com/unreal-engine/announcements-and-releases/1612034-4-22-1-hotfix-released):

> Fixed! UE-71586 Unable to compile code projects from installed build on Linux

As such, I would recommend that you rebuild your images using Unreal Engine 4.22.1 to ensure that you will be able to build and package projects successfully.

**Comment by hxdnshx** [comment]
Thanks for your reply.
By your comment, I noticed that ue4-build-prerequisites would not rebuild when the base-image changed(although base-image is not able to change in ue4-docker cli), so I should remove prerequisites image, drop my modification and rebuild all.

the base image used in this issue is nvcr.io/nvidia/tensorrt:18.08-py2 with py3,ros and opencv3.4.0.

Copying ue4 form host system is just because the network is too unstable to download ue4 repository(and docker doesn't cache the intermediate container of step "git clone".)
