### ISSUE TITLE
Building for Windows on a Linux host

### ISSUE THREAD

**Issue by gcandal** [adamrehn/ue4-docker#36]
First of all, let me thank you for your hard work on ue4-docker and sharing it with the community :)

This is more of a question rather than a bug report or feature request, so I apologize if this is not the correct forum.

**Is it possible to package projects for Windows when running on a Linux host?** By looking at the [feature support matrix](https://unrealcontainers.com/docs/obtaining-images/image-sources#feature-support-matrix) and the [supported host configurations](https://adamrehn.com/docs/ue4-docker/configuration/supported-host-configurations) it seems the answer is *no*, but I'd like to be sure.

Also, could you please try and briefly explain why that is?

Thanks in advance!

**Comment by adamrehn** [comment]
Thanks, I'm glad you've found ue4-docker useful!

Unfortunately the Unreal Engine currently only supports cross-compilation for Linux from Windows, not the other way around. The way that Windows-to-Linux cross compilation is achieved is by bundling a copy of the open source [clang compiler](https://clang.llvm.org/) along with a set of standard C and C++ libraries, primarily the [libc++](https://libcxx.llvm.org/) standard library implementation. The entire Linux cross-compilation toolchain is open source and can be freely bundled with the Engine, making integration with the Unreal Engine's build tools relatively straightforward.

Cross-compilation for Windows from Linux is a very different proposition. The Windows SDK can typically only be installed under Linux using the [Wine project](https://www.winehq.org/), and this configuration is not supported by Microsoft. Although it is possible to use the [clang-cl compiler driver](https://clang.llvm.org/docs/MSVCCompatibility.html) to perform cross-compilation, doing so still requires the headers and library files from the Windows SDK. Since the Windows SDK is not open source it cannot simply be bundled with the Unreal Engine. (Bundling it would also be impractical due to its prohibitive size, weighing in at multiple gigabytes with all of the libraries and build tools.) In practice, most C++ developers who want to cross-compile for Windows from Linux use the open source [MinGW toolchain](https://mingw-w64.org/) to do so, but this comes with its own set of challenges and the MinGW library implementation often takes quite some time to achieve feature parity with the latest version of Visual Studio. Given these complexities, it's unsurprising that the developers at Epic Games have opted to avoid the issue entirely by simply not supporting Windows compilation from other platforms.

If this situation ever changes and Linux-to-Windows cross-compilation of the Unreal Engine becomes supported, I'll be one of the first people to jump aboard. The Windows container images have been the source of [the majority of the issues I've encountered](https://adamrehn.com/docs/ue4-docker/building-images/troubleshooting-build-issues#windows-specific-issues) during the development of ue4-docker, so working with only Linux container images would be a tremendous relief. In the meantime, however, compilation under a Windows host system is the only way to package projects for Windows target systems.
