### ISSUE TITLE
Including marketplace plugins

### ISSUE THREAD

**Issue by gcandal** [adamrehn/ue4-docker#38]
This is more of a question than anything else: what is the recommended way to include third-party plugins?

Right now I'm thinking about copying the specific version of the plugin (in this case, *Substance in Unreal Engine*) to the `Plugins` folder of my project, but what would be interesting was to somehow achieve the same objective during the compilation of the Engine itself rather than the project's.

Another option would be to have an image built on top of `ue4-source` and then use it for `ue4-engine` and `ue4-minimal`. Does this sound reasonable?

**Comment by adamrehn** [comment]
If the plugin that you'd like to bundle already contains precompiled binaries for your target platform (as is the case for Marketplace plugins under Windows), then you can simply copy the plugin into the Engine's plugins directory after the Engine itself has been built and everything will work correctly. This will typically take the form of a new image built on top of the `ue4-minimal` or `ue4-full` image. Alternatively, some developers [perform the copy when they build their project](https://github.com/deepdrive/deepdrive-sim/blob/826c77374256b274274b61b47d3d4fa195cd4926/Packaging/package.py#L56-L59) as part of their CI pipeline. This latter approach allows you to change the version of the plugin that you want to use without the need to rebuild any container images, but requires that you have a copy of the plugin available for extraction each time the CI pipeline runs. The approach you choose will obviously depend on your own requirements and preferences.

If the plugin that you'd like to bundle **does not** contain precompiled binaries for your target platform (e.g. when using a Marketplace plugin under Linux) then my recommended approach would be to compile it using either [ue4cli](https://github.com/adamrehn/ue4cli) or a direct call to Unreal AutomationTool and then copy it into a prebuilt Unreal Engine installation after that. (For maximum platform support, you can even [merge built Linux binaries with prebuilt Windows and Mac binaries](https://github.com/deepdrive/SubstanceDocker/blob/master/Packaging/package.py) to produce a plugin distribution that will work on all three platforms.) This is significantly more convenient than building the plugin as part of the Engine's build process because you don't need to rebuild the entire Engine each time you update to a new version of the plugin. You could use a Docker [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/) to copy the built plugin into a new container image based on either `ue4-minimal` or `ue4-full`, or create a zip file if you want to take the approach of copying the plugin during the CI process for your project.

It's worth noting that the Substance plugin in particular includes a hard-coded check to ensure it's been placed in a subdirectory consistent with a Marketplace installation, so you'll want to copy it into the `Engine/Plugins/Marketplace` directory specifically. By contrast, most other plugins can be placed anywhere inside `Engine/Plugins` and they'll work happily.

**Comment by adamrehn** [comment]
I'm going to leave this issue open as a reminder to myself to add a section covering plugin development and integration to the [CI/CD page of the Unreal Containers documentation](https://unrealcontainers.com/docs/use-cases/continuous-integration). In the meantime, if you have any follow-up questions regarding this topic then I'll be happy to address those details and include them in the documentation as well.

**Comment by adamrehn** [comment]
A new section covering the relevant materials from this thread has now been added to the Unreal Containers documentation: https://unrealcontainers.com/docs/use-cases/continuous-integration#using-prebuilt-unreal-plugins
