### ISSUE TITLE
Use all cores in ue4 build

### ISSUE THREAD

**Issue by ki11roy** [adamrehn/ue4-docker#40]
How to use all the cores in ue4 build? It seems that it uses only two by default:
```
12:57:00]	[Step 2/3] Reflection code generated for juydEditor in 15.2554895 seconds
[12:57:02]	[Step 2/3] Using Visual Studio 2017 14.16.27023 toolchain (C:\BuildTools\VC\Tools\MSVC\14.16.27023) and Windows 10.0.17763.0 SDK (C:\Program Files (x86)\Windows Kits\10).
[12:57:02]	[Step 2/3] Building 31 actions with 2 processes...
```

**Comment by adamrehn** [comment]
Under Windows hosts, process isolation mode will use all available CPU cores, whereas VMs spawned by Hyper-V isolation mode [only have access to two CPU cores by default](https://github.com/docker/for-win/issues/1877). Are you using process isolation mode or Hyper-V isolation mode?

**Comment by ki11roy** [comment]
Correct, I am in Hyper-V mode.

**Comment by adamrehn** [comment]
In that case the behaviour you're seeing is expected. For maximum performance I would recommend using process isolation mode if possible, since Hyper-V isolation mode [suffers from a number of issues](https://unrealcontainers.com/docs/concepts/windows-containers#hyper-v-isolation-mode-issues) in addition to the CPU core limit that make it poorly suited to building large, complex container images such as those produced by ue4-docker. Process isolation mode will be used by default if you're running the latest version of ue4-docker with Docker 18.09 under [Windows 10 version 1809 or newer](https://docs.microsoft.com/en-us/virtualization/windowscontainers/about/faq#can-i-run-windows-containers-in-process-isolated-mode-on-windows-10-enterprise-or-professional).

**Comment by ki11roy** [comment]
Thanks!
