### ISSUE TITLE
Don't prompt for username/password if ue4-source image won't be built

### ISSUE THREAD

**Issue by TBBle** [adamrehn/ue4-docker#42]
It'd be super-convenient if in the presence of an appropriately-tagged `_UE4DOCKER_TAG_NAMESPACE_/ue4-source` image, and absence of the `--rebuild` parameter, the CLI didn't prompt for a username/password, since it's not going to use it.

I haven't looked... I hope this is simple, but I understand that it might have to be parked behind #22.

**Comment by adamrehn** [comment]
The simple workaround for the time being is to simply specify a dummy password via command-line arguments (e.g. `-username=dummy -password=dummy`) when you know that the `ue4-source` image is already built, but I agree that it'd be better in the long run if the build command was smart enough to know when credentials are and are not required. I'll have a think about how best to achieve that.

**Comment by adamrehn** [comment]
Okay, an implementation of this is now live in ue4-docker 0.0.35. I've refactored the `ImageBuilder` class a bit so that it can be queried from the build command to determine whether a given image will be built or not, and credentials are only retrieved if the `ue4-source` image is going to be built.

On an unrelated note, the code in the latter half of `build.py` has become something of a tangled, convoluted mess. I remember thinking that it was getting a bit messy the last time I had to modify it, but I'd forgotten just how bad it was. I'm going to leave it as it is for the moment, since it's working nicely, but when I eventually get around to my planned redesign of ue4-docker to accommodate multiple Visual Studio base images (2015/2017/2019/etc.) and cross-compilation images (Windows to Linux, Windows to Android, etc.) then I'm gonna throw that code out and replace it with a more elegant dependency graph-based system.
