### ISSUE TITLE
Missing precompiled manifest for AutomationDriver

### ISSUE THREAD

**Issue by galeone** [adamrehn/ue4-docker#61]
Output of the `ue4-docker info` command:

```
ue4-docker version:         0.0.44 (latest available version is 0.0.45)
Operating system:           Linux (Arch Linux, 5.4.3-arch1-1)
Docker daemon version:      19.03.5-ce
NVIDIA Docker supported:    Yes
Maximum image size:         No limit detected
Available disk space:       137.59 GiB
Total system memory:        62.5 GiB physical, 1024 MiB virtual
Number of processors:       8 physical, 16 logical
```

I'm trying to execute inside a container the tests for a software (that are placed inside a separate plugin, as by epic recommendation), with the usage of AutomationDriver (https://docs.unrealengine.com/en-US/Programming/Automation/AutomationDriver/index.html)

However, when I invoke the UBT to build the application, I got this error

```
ERROR: Missing precompiled manifest for 'AutomationDriver'. This module was most likely not flagged for being included in a precompiled build - set 'PrecompileForTargets = PrecompileTargetsType.Any;' in AutomationDriver.build.cs to override.
```

Perhaps this feature should be enabled while building the engine?

The "strange" thing (I guess) is that if I run the build step, using the UBT I go the error
```
mono ~/UnrealEngine/Engine/Binaries/DotNET/UnrealBuildTool.exe Project Linux Development -project=$(pwd)/Project.uproject
```

While if I execute `ue4 build`  the compilation starts correctly - is this the expected behavior?

**Comment by adamrehn** [comment]
Thanks for reporting this, I will investigate further when I return to work in January.

**Comment by galeone** [comment]
Thank you! Also a quick update: the same error happens when I run `ue4 package` (I get the same error about Missing precompiled manifest)

**Comment by adamrehn** [comment]
I'm glad you were able to determine the cause of the problem.

The difference between the [ue4 build](https://adamrehn.com/docs/ue4cli/descriptor-commands/build) command and your manually-crafted UBT call is that ue4cli will build the Editor target for a project by default (i.e. `ProjectEditor Linux Development`), whereas you've explicitly specified the non-Editor target (`Project Linux Development`), which is why the ue4cli command was successfully building Editor-only plugins and thus avoiding the issue that you encountered.

To improve visibility into the inner workings of ue4cli, I've added support for setting an environment variable to enable verbose output (`set UE4CLI_VERBOSE=1`), which will cause ue4cli to print any UBT or UAT commands that it runs as child processes. Support for verbose output is live in [ue4cli version 0.0.40](https://github.com/adamrehn/ue4cli/releases/tag/v0.0.40).
