### ISSUE TITLE
Feature Request: Ubuntu Version Control

### ISSUE THREAD

**Issue by AutonomousHansen** [adamrehn/ue4-docker#71]
Currently the default Ubuntu version is 18.04, but I'm wondering if there is a way to make this configurable so that 16.04 is the target version? I notice that in the runtime containers there are 16.04 versions, so I was hopeful. Thanks!

**Comment by adamrehn** [comment]
Infrastructure changes to support a wider variety of base images and configurations is being planned as part of #48, so you can track the progress of the feature there. Out of curiosity, what use case is motivating the need for an Ubuntu 16.04 version?

**Comment by AutonomousHansen** [comment]
We have a software stack which targets 16.04, and we were looking for something which  is compatible. We actually found a way to circumvent that need, though it would still be cool to have it if free. Thanks for the response!

**Comment by adamrehn** [comment]
Just for the record in case anyone else finds this issue and isn't clear on this distinction: the binaries produced by packaging an Unreal Engine project in a ue4-docker container image based on Ubuntu 18.04 will happily run in an Ubuntu 16.04 variant of the [ue4-runtime](https://github.com/adamrehn/ue4-runtime) container image, since UE4 bundles its own clang toolchain and CentOS 7 sysroot in order to ensure wide compatibility with different versions of Linux.

The only reason someone would need an Ubuntu 16.04 version of the ue4-docker container images (as requested here) is if the software you are using at ***compile time*** is something that requires that version of Ubuntu. Even in that case, you can still copy the Installed Build of UE4 from the [ue4-minimal](https://adamrehn.com/docs/ue4-docker/building-images/available-container-images#ue4-minimal) or [ue4-full](https://adamrehn.com/docs/ue4-docker/building-images/available-container-images#ue4-full) container images into a separate image based on a different version of Ubuntu, since the Engine itself is also built with the same toolchain and sysroot. So if you find yourself in the same boat as @AutonomousHansen was but can't find a way around the requirement for a specific version of Ubuntu, there's still a solution readily available to you while the infrastructure redesign process is ongoing.
