### ISSUE TITLE
Vulkan SDK Deprecated

### ISSUE THREAD

**Issue by ShiroiKuma** [adamrehn/ue4-docker#82]
The Vulkan SDK downloaded here is obsolete now it seems and no longer downloadable (went down in the last 10 days or so at some point), bumping the minor version to 85 works (the current oldest version downloadable.)

https://github.com/adamrehn/ue4-docker/blob/0ea6c0025eb595e67335f6bb1b0ec18dbcddb010/ue4docker/dockerfiles/ue4-build-prerequisites/windows/Dockerfile#L37

Still building (providing my server doesn't reboot spontaneously again) and can run the ue4-docker tests in a few days to confirm success or not.

**Comment by adamrehn** [comment]
Thanks for reporting this! Fortunately it turns out you can now download the runtime separately from the SDK, so we can save some time and download a tiny zip archive instead of a massive SDK installer. I've switched to using the download link for the latest runtime in commit 526baac, so hopefully that link should remain stable going forward.
