### ISSUE TITLE
Minimum system requirements? 

### ISSUE THREAD

**Issue by dskvr** [adamrehn/ue4-docker#85]
I have been unable to find minimum system requirements for building ue4-docker, and was curious if these were posted anywhere I'm not looking. I'm attempting to build with `ue4-docker` in an EC2 pipeline, but it always fails, for both Windows and Linux. 

I have been systematically upgrading the instances, and with each upgrade, I get further along in the build. That said, I wouldn't have to wait a day in between each test if I understood the minimum system requirements in terms of **core count** and **memory** that are required for a build to complete. I have found storage requirements, being 300gb for Linux and 500gb for Windows, so thanks for that. 

I understand if you cannot provide perfectly accurate system requirements given the state of Unreal development, but I assume you've had successful builds and can advise on what your system was composed of.  

Unfortunately I cannot provide logs, as I cannot access them. The pipeline runs with a self-hosted Github Actions runner, and the Github Actions GUI crashes when attempting to load the 19 hours worth of logs. I'm in the process of adding better logging to the build so that this is a non-issue. 

With my limited visibility, it appears Windows and Linux builds both fail at approximately the same step in the build, as they fail ~5-20 minutes apart from each other. Again, I'll have more details soon. 

**Edit** Forgot to mention, the EC2 instances are _Unlimited_ so CPU credits aren't the problem.

**Comment by adamrehn** [comment]
Epic provides recommended system requirements for building and running the Unreal Editor here: https://docs.unrealengine.com/en-US/GettingStarted/RecommendedSpecifications/index.html

I've personally never tested building UE4 container images with less than 8 CPU cores and 16GiB of memory, simply because it takes so damn long to build even with those specs. If you're building Windows container images then it's also worth noting that the compiler [may crash if the host system's pagefile is not set to a sufficiently large size](https://adamrehn.com/docs/ue4-docker/building-images/troubleshooting-build-issues#building-the-engine-in-a-windows-container-fails-with-the-message-fatal-error-c1060-the-compiler-is-out-of-heap-space). I typically set it to at least 50% the amount of system memory as a general rule of thumb, but some experimentation is usually required to determine the ideal size.

**Comment by dskvr** [comment]
Wonderful, thanks @adamrehn!
