### ISSUE TITLE
Disabling core dumps. error: XDG_RUNTIME_DIR not set in the environment.

### ISSUE THREAD

**Issue by CoWillChen** [adamrehn/ue4-docker#86]
I packaged a project in ue4-full container, and run the .sh file by command "sh mygame.sh", but it failed showing:"Disabling core dumps. error: XDG_RUNTIME_DIR not set in the environment.", any help?  Thanks!

**Comment by adamrehn** [comment]
That message does not indicate a failure, that is the expected output when running a project packaged in the Shipping configuration. If your project is actually failing to start (rather than simply running successfully with no log output) then you will need to re-package it in the Development configuration (e.g. by running `ue4 package Development` if you're using ue4cli) and then run the shell script for the Development build to inspect its log output, which should include a crash dump.

**Comment by MrZivChu** [comment]
@CoWillChen 
Hello, friend, have you solved your problem? Can you share the solution？Thank you

**Comment by adamrehn** [comment]
As stated previously, this is almost certainly a misunderstanding of how the Unreal Engine behaves in a headless environment and not an actual crash. Given the lack of any further details to contradict this, I'm going to close this issue.
