### ISSUE TITLE
Documentation on argument placement for ue4-docker build is ambiguous

### ISSUE THREAD

**Issue by dskvr** [adamrehn/ue4-docker#87]
From [ue4-docker build reference](https://adamrehn.com/docs/ue4-docker/commands/build)
```
ue4-docker build [-h] [--linux] [--rebuild] [--dry-run]
                 [--pull-prerequisites] [--no-engine] [--no-minimal]
                 [--no-full] [--no-cache] [--random-memory]
                 [--exclude {debug,templates}] [--cuda VERSION]
                 [-username USERNAME] [-password PASSWORD] [-repo REPO]
                 [-branch BRANCH] [-isolation ISOLATION]
                 [-basetag BASETAG] [-dlldir DLLDIR] [-suffix SUFFIX]
                 [-m M]
                 release
```

which suggests the following usage:

`ue4-docker build --linux 4.25.1` 

However, elsewhere in the documentation, for example in [Advanced build options](https://adamrehn.com/docs/ue4-docker/building-images/advanced-build-options#keeping-or-excluding-installed-build-debug-symbols-under-windows) the examples suggest usage is 

`ue4-docker build 4.25.1 --linux` 

Maybe arguments are parsed in both scenarios? Regardless of this, the reference documentation should likely align with the other examples of `ue4-docker build`

**Comment by adamrehn** [comment]
The ordering on that page is directly reproduced from the output of `ue4-docker build --help` and is generated automatically by the Python [argparse](https://docs.python.org/3/library/argparse.html) module, so any changes would need to involve a manual editing step each time the page is updated, which I'm hesitant to introduce. The command will work correctly regardless of the order in which the arguments are specified, so the order that a given user decides to specify them is entirely a matter of preference. Personally, I always put the Unreal Engine release number first and specify the other flags afterwards because I find it clearer to read, and that preference is reflected in the examples throughout the documentation, but it's not by any means mandatory.

It's worth noting that this parsing behaviour is fairly standard at the broader level outside ue4-docker. Most command-line tools that use standard argument parsing libraries will accept optional arguments in any order (including interspersed between positional arguments) so long as any positional arguments are specified in the correct order relative to one another. Notable examples are tools which allow the user to specify arbitrary arguments to be propagated to other tools that get run as child processes, which will typically require the additional arguments be placed after a given positional argument, or else delineated from the entirety of the rest of the command by a double dash (`--`). I'm also aware of some tools such as [FFmpeg](https://ffmpeg.org/) that rely on the specific placement of flags relative to one another to determine their meaning, such as seeking to a given starting time in a particular input file.

**Comment by dskvr** [comment]
Got it! I asked because after many hours of failed builds one starts to look into every possible cause of failure, and this inconsistency causes doubt. There are definitely many command line tools that require arguments in specific places, but when I posted this I failed to register the `RELEASE` as just another argument. Additionally, I have experience with `argparse` and should have known better ;)
