### ISSUE TITLE
Use case for In-Game Development Engine Automation with rendering system

### ISSUE THREAD

**Issue by desjare** [adamrehn/ue4-docker#90]
It would be nice to have a workflow when you can actually deploy an unreal game and run it for automation. You can start Unreal with an exec command that could trigger any gameplay workflow, script, or AI-controlled Pawn and collect information about your tests. 

An image could be built on each version and tests could run automatically.

This would be rather interesting to simulate multiplayer workflows by deploying the same container on several hosts and connect them to one another.

Hopefully, I followed your contributing guidelines.

Kind Regards

**Comment by adamrehn** [comment]
Apologies for the delay in responding to this issue, I've been inordinately busy over the past couple of months and I'm only now making my way through my GitHub backlog.

The system you're describing (albeit without the use of containers) is the [Gauntlet Automation Framework](https://docs.unrealengine.com/en-US/Programming/Automation/Gauntlet/index.html), which has shipped with the Unreal Engine since version 4.21.0. Integration between Gauntlet and Unreal Engine containers has been on my list of things to investigate for quite some time now, so I'll treat this as a +1 for encouraging that investigation.
